In [1]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
sns.set(style="darkgrid")
from time import time

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

# Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.metrics import fbeta_score
from sklearn.metrics import accuracy_score
# Import the three supervised learning models from sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA    

# Pretty display for notebooks
%matplotlib inline
from random import shuffle

In [1]:
#NG
import time
import pulp as p 
def min_sum_lpca(data1,beta,eps,e,alpha):
    import pulp as p 
    import math
    #for bilal
    #beta=[beta1[1], beta1[0],beta1[6],beta1[4],beta1[3],beta1[2],beta1[5]]
    #print(beta)
    m=data1.shape[0]
    n=data1.shape[1]
    print('dimension of data')
    print(m,n)
    
    ################ sorted result
    a1=0
    a2=0
    b1=0
    b2=0
    c1=0
    c2=0
    d1=0
    d2=0
    e1=0
    e2=0
    h1=[]
    h2=[]
    h3=[]
    h4=[]
    h5=[]
    h6=[]
    h7=[]
    key1=[]
    key2=[]
    key3=[]
    key4=[]
    key5=[]
    key6=[]
    key7=[]
    cost=np.zeros(n,dtype=int)
    data2=np.zeros((m,n),dtype=int)
    for i in range(n):
        if data1[0][i]==1:            

            h1.append(e[i][1])
            key1.append(i)
            if data1[2][i]==1:
                a1=a1+1
            elif data1[3][i]==1:
                b1=b1+1
            elif data1[4][i]==1:
                c1=c1+1 
            elif data1[5][i]==1:
                d1=d1+1
            elif data1[6][i]==1:
                e1=e1+1

        elif data1[1][i]==1:
            h2.append(e[i][1])
            key2.append(i)
            if data1[2][i]==1:
                a2=a2+1
            elif data1[3][i]==1:
                b2=b2+1
            elif data1[4][i]==1:
                c2=c2+1 
            elif data1[5][i]==1:
                d2=d2+1
            elif data1[6][i]==1:
                e2=e2+1
            
        if data1[2][i]==1:
            h3.append(e[i][1])
            key3.append(i)
            
        elif data1[3][i]==1:
            h4.append(e[i][1])
            key4.append(i)
        elif data1[4][i]==1:
            h5.append(e[i][1])
            key5.append(i)
        elif data1[5][i]==1:
            h6.append(e[i][1])
            key6.append(i)
        elif data1[6][i]==1:
            h7.append(e[i][1])
            key7.append(i)
#print(hc)
#     print(key1)
    
    for i in range(1,len(h1)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h1[j-1]<h1[j]:
                index=j
                var=h1[j]
                h1[j]=h1[j-1]
                h1[j-1]=var

                var2=key1[j]
                key1[j]=key1[j-1]
                key1[j-1]=var2
            else:
                break
    

    for i in range(1,len(h2)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h2[j-1]<h2[j]:
                index=j
                var=h2[j]
                h2[j]=h2[j-1]
                h2[j-1]=var

                var2=key2[j]
                key2[j]=key2[j-1]
                key2[j-1]=var2
            else:
                break
    for i in range(1,len(h3)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h3[j-1]<h3[j]:
                index=j
                var=h3[j]
                h3[j]=h3[j-1]
                h3[j-1]=var

                var2=key3[j]
                key3[j]=key3[j-1]
                key3[j-1]=var2
            else:
                break
    for i in range(1,len(h4)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h4[j-1]<h4[j]:
                index=j
                var=h4[j]
                h4[j]=h4[j-1]
                h4[j-1]=var

                var2=key4[j]
                key4[j]=key4[j-1]
                key4[j-1]=var2
            else:
                break
    for i in range(1,len(h5)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h5[j-1]<h5[j]:
                index=j
                var=h5[j]
                h5[j]=h5[j-1]
                h5[j-1]=var

                var2=key5[j]
                key5[j]=key5[j-1]
                key5[j-1]=var2
            else:
                break
                
                
                
    for i in range(1,len(h6)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h6[j-1]<h6[j]:
                index=j
                var=h6[j]
                h6[j]=h6[j-1]
                h6[j-1]=var

                var2=key6[j]
                key6[j]=key6[j-1]
                key6[j-1]=var2
            else:
                break        
                

    for i in range(1,len(h7)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h7[j-1]<h7[j]:
                index=j
                var=h7[j]
                h7[j]=h7[j-1]
                h7[j-1]=var

                var2=key7[j]
                key7[j]=key7[j-1]
                key7[j-1]=var2
            else:
                break 
    '''            
    
    for j in range(len(key1)):    
        if h1[j]==h1[j-1] and j>=1:
            data2[0][key1[j]]=data2[0][key1[j-1]]
        else:    
            data2[0][key1[j]]=j+1
    for j in range(len(key2)):
        if h2[j]==h2[j-1] and j>=1:
            data2[1][key2[j]]=data2[0][key2[j-1]]
        else:    
            data2[1][key2[j]]=j+1
    for j in range(len(key3)):
        if h3[j]==h3[j-1] and j>=1:
            data2[2][key3[j]]=data2[2][key3[j-1]]
        else:    
            data2[2][key3[j]]=j+1
    for j in range(len(key4)):
        if h4[j]==h4[j-1] and j>=1:
            data2[3][key4[j]]=data2[3][key4[j-1]]
        else:    
            data2[3][key4[j]]=j+1
    for j in range(len(key5)):
        if h5[j]==h5[j-1] and j>=1:
            data2[4][key5[j]]=data2[4][key5[j-1]]
        else:    
            data2[4][key5[j]]=j+1
    for j in range(len(key6)):
        if h6[j]==h6[j-1] and j>=1:
            data2[5][key6[j]]=data2[5][key6[j-1]]
        else:    
            data2[5][key6[j]]=j+1
    for j in range(len(key7)):
        if h7[j]==h7[j-1] and j>=1:
            data2[6][key7[j]]=data2[6][key7[j-1]]
        else:    
            data2[6][key7[j]]=j+1 
    
  ###############################1#################################  
    #2nd approach
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*alpha[1]
    for j in range(len(key3)):
        if data1[2][key3[j]]==1 and data1[0][key3[j]]==1: 
            data2[2][key3[j]]=(j+1)*(len(key1)/len(key3))*alpha[2]
        else:
            data2[2][key3[j]]=(j+1)*(len(key2)/len(key3))*alpha[2]                  
        
    for j in range(len(key4)):
        if data1[3][key4[j]]==1 and data1[0][key4[j]]==1:                   
            data2[3][key4[j]]=(j+1)*(len(key1)/len(key4))*alpha[3]
        else :                     
            data2[3][key4[j]]=(j+1)*(len(key2)/len(key4))*alpha[3]
                             
    for j in range(len(key5)):
        if data1[4][key5[j]]==1 and data1[0][key5[j]]==1:                  
            data2[4][key5[j]]=(j+1)*(len(key1)/len(key5))*alpha[4]
        else:      
            data2[4][key5[j]]=(j+1)*(len(key2)/len(key5))*alpha[4]
    for j in range(len(key6)):
        if data1[5][key6[j]]==1 and data1[0][key6[j]]==1:                    
            data2[5][key6[j]]=(j+1)*(len(key1)/len(key6))*alpha[5]
        else:                    
             data2[5][key6[j]]=(j+1)*(len(key2)/len(key6))*alpha[5]               
    for j in range(len(key7)):
        if data1[6][key7[j]]==1 and data1[0][key7[j]]==1:
            data2[6][key7[j]]=(j+1)*(len(key1)/len(key7))*alpha[6]
        else:
             data2[6][key7[j]]=(j+1)*(len(key2)/len(key7))*alpha[6]
    '''
    '''
    
    #1st approach
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*alpha[1]
    for j in range(len(key3)):
        data2[2][key3[j]]=(j+1)*alpha[2]              
        
    for j in range(len(key4)):
        data2[3][key4[j]]=(j+1)*alpha[3]
        
                             
    for j in range(len(key5)):               
        data2[4][key5[j]]=(j+1)*alpha[4]
       
    for j in range(len(key6)):
        data2[5][key6[j]]=(j+1)*alpha[5]
                    
    for j in range(len(key7)):
        data2[6][key7[j]]=(j+1)*alpha[6]
    '''   
    '''
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*((beta[0]*len(key1))/(beta[1]*len(key2)))*alpha[1]
    for j in range(len(key3)):
        data2[2][key3[j]]=(j+1)*((beta[2]*len(key3))/(beta[2]*len(key3)))*alpha[2]
                         
        
    for j in range(len(key4)):           
        #data2[3][key4[j]]=(j+1)*((beta[2]*len(key3))/(beta[3]*len(key4)))*alpha[3]
        if data1[3][key4[j]]==1 and data1[0][key4[j]]==1:                   
            data2[3][key4[j]]=(j+1)*((beta[2]*len(key3))/(beta[3]*len(key4)))*alpha[3]
        else :                     
            data2[3][key4[j]]=(j+1)*((beta[2]*len(key3))/(beta[3]*len(key4)))*alpha[3]
                             
    for j in range(len(key5)):
        data2[4][key5[j]]=(j+1)*((beta[2]*len(key3))/(beta[4]*len(key5)))*alpha[4]      
    for j in range(len(key6)):                 
        data2[5][key6[j]]=(j+1)*((beta[2]*len(key3))/(beta[5]*len(key6)))*alpha[5]  
    for j in range(len(key7)):                 
        data2[6][key7[j]]=(j+1)*((beta[2]*len(key3))/(beta[6]*len(key7)))*alpha[6] 
    '''
    #######################################################################    
    
    ####################################################################### 
   
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*((beta[1]*len(key2))/(beta[0]*len(key1)))*alpha[1]
    
    for j in range(len(key3)):
        data2[2][key3[j]]=(j+1)*alpha[2]
                         
        
    for j in range(len(key4)):           
        #data2[3][key4[j]]=(j+1)*((beta[2]*len(key3))/(beta[3]*len(key4)))*alpha[3]
        if data1[3][key4[j]]==1 and data1[0][key4[j]]==1:                   
            data2[3][key4[j]]=(j+1)*((beta[3]*len(key4))/(beta[2]*len(key3)))*alpha[3]
        else :                     
            data2[3][key4[j]]=(j+1)*((beta[3]*len(key4))/(beta[2]*len(key3)))*alpha[3]
                             
    for j in range(len(key5)):
        data2[4][key5[j]]=(j+1)*((beta[4]*len(key5))/(beta[2]*len(key3)))*alpha[4]
       
           
    for j in range(len(key6)):                 
        data2[5][key6[j]]=(j+1)*((beta[5]*len(key6))/(beta[2]*len(key3)))*alpha[5]
    
    for j in range(len(key7)):                 
        data2[6][key7[j]]=(j+1)*((beta[6]*len(key7))/(beta[2]*len(key3)))*alpha[6]    
        
        
    for j in range(n):
        summ=0
        for i in range(m):
       
            summ=summ+data2[i][j] 
        cost[j]=summ
        
        
    ################
    
    
    Lp_prob = p.LpProblem('Problem', p.LpMinimize)  
   
    
#     X=np.zeros(n+1,dtype=p.LpVariable)
    X=np.zeros(n+m+1,dtype=p.LpVariable)
    sizes=np.zeros(m,dtype=int)
#     report_index(index,data1,e):  
    max_size=0
    for i in range(m):
        count=0
        for j in range(n):
            if data1[i][j]==1:
                count=count+1 
        if count>max_size:
            max_size=count
        sizes[i]=count
    print(sizes)    
    #############################33
    
    
    
    
    ###############################
        
        
        
  
    select_sizes=np.zeros(m,dtype=int)
   
    size_final=np.zeros(m,dtype=int)

    
    for i in range(n):
        var1=str(i)       
        X[i]=p.LpVariable(var1,lowBound=0,upBound=1,cat='Integer')
   
    X[n]=p.LpVariable(str(n),lowBound=0,upBound=1,cat='Continuous')  

  

    #########objective function#####################
    
#     Lp_prob += 2*X[n+1]+10*X[n+2]+9*X[n+3]+3*X[n+4]
    
    Lp_prob+= p.lpSum([(X[j])*cost[j] for j in range(n)]) 
    #Lp_prob+=1  
    

    ##############constraint#################
    for i in range(2*m):
        if i<m:

            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) >= math.floor(beta[i]*sizes[i])
            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) <= math.ceil((beta[i]+eps)*sizes[i])
           # Lp_prob += p.lpSum([(X[j])*(data1[i][j])*(sizes[i]-report_index(j,i,data1,e)+1) for j in range(n)]) <= X[n+i+1]
                    

        
    #####################################
    status = Lp_prob.solve()   # Solver 
    print(p.LpStatus[status]) 
    print("objective is:")        
    print(p.value(Lp_prob.objective))
    print("discripency is:") 
    print(p.value(X[n]))
    x=np.zeros(n,dtype=float)

   # The solution status 
    Synth1={}
    Synth2={}
    # # Printing the final solution 
    for i in range(n):
        if(p.value(X[i])==1):
            Synth1[i]=1 
            Synth2[i]=-1
#             if(data1[2][i]==1):
#                 print("no")
        else:
            Synth1[i]=-1
            Synth2[i]=1
    Synthu1=Synth1  
    Synthu2=Synth2  
    
              
    return Synthu1,Synthu2   


In [13]:
#SVM 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%pylab inline
from random import *
from subprocess import check_output
def adult_svm(X,Y):
    #Split data into training and test datasets (training will be based on 70% of data)
    from sklearn.model_selection import train_test_split
    
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0,shuffle=True) 
    #test_size: if integer, number of examples into test dataset; if between 0.0 and 1.0, means proportion
    print('There are {} samples in the training set and {} samples in the test set'.format(X_train.shape[0], X_test.shape[0]))

    
    #Scaling data
    #from sklearn.preprocessing import StandardScaler
    
    from sklearn.model_selection import cross_val_score

    #sc = StandardScaler(with_mean=False)
    
    
    #sc.fit(X_train)
    #X_train_std = sc.transform(X_train)
    #X_test_std = sc.transform(X_test)

    #X_train_std and X_test_std are the scaled datasets to be used in algorithms

    #Applying SVC (Support Vector Classification)
    from sklearn.svm import SVC
    svm = SVC(kernel='rbf', random_state=0, gamma=.1, C=10.0,probability=True)
    
    print(Y_train.dtypes)
    Y_train=Y_train.astype('int')
    print(Y_train.dtypes)
    
    print(Y_test.dtypes)
    Y_test=Y_test.astype('int')
    print(Y_test.dtypes)
    
    
    svm.fit(X_train, Y_train)
    print('The accuracy of the SVM classifier on training data is {:.2f}'.format(svm.score(X_train, Y_train)))
    print('The accuracy of the SVM classifier on test data is {:.2f}'.format(svm.score(X_test, Y_test)))
    print('####Train prediction Label###############################################')
    Y_train_pred=svm.predict(X_train)
    #print(y_1)
    Y_test_pred=svm.predict(X_test)

    print('####Actual Train Label###############################################')


    print('####Change to colors###############################################')
        
    e=svm.predict_proba(X_test)
    print(e)
    return X_test,Y_test_pred,Y_test,e
     



Populating the interactive namespace from numpy and matplotlib


/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['shuffle']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [42]:
#without accuracy ---> 2
def main(datax, y_test, y_test_pred,e): 
        
    n=datax.shape[1]
    s=datax.shape[0]    
    data = np.zeros((s, n), dtype = int)
    
    r = np.zeros(n, dtype = int) 
    
    for i in range(n):
        if int(y_test.iloc[i])==1 :
            r[i]=1
        else :
            r[i]= -1  
    
    r2 = np.zeros(n, dtype = int) 
    for i in range(n):
        if int(y_test_pred[i])==1 :
            r2[i]=1
        else :
            r2[i]= -1          
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        for i in range(n):
                data[j][i]= datax.iloc[j,i]
                if data[j][i]== 1 :
                    a=a+1
                    if r[i]==1:
                         acc1=acc1+1 

        print("ACTUAL----------total ,accepted, aceeptance rate:")             
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP)
    
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        prec=0
        reca=0
        accur=0
        FP=0
        FN=0
        TP=0
        TN=0
        for i in range(n):
             if data[j][i]== 1 :
                    a=a+1
                    if r2[i]==1:
                        acc1=acc1+1 
                        if r[i]==1:
                            TP=TP+1
                        else:
                             FP=FP+1                
                    else:
                        if r[i]==1:
                            FN=FN+1
                        else:
                            TN=TN+1    
        
        print("prec reca accuracy for each sens") 
        prec= float(TP/(TP+FP))
        reca= float(TP/(TP+FN))
        accur= float((TP+TN)/a)
        print(prec,reca,accur)
        
        print("SVM----------total , accepted, aceeptance rate:")             
        
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP) 
    
    print("SVM accuracy--------------------------")
    prec=0
    reca=0
    accur=0
    FP=0
    FN=0
    TP=0
    TN=0
    for i in range(n):
            if r2[i]==1:
                acc1=acc1+1 
                if r[i]==1:
                    TP=TP+1
                else:
                     FP=FP+1                
            else:
                if r[i]==1:
                     FN=FN+1
                else:
                     TN=TN+1    

        
    prec= float(TP/(TP+FP))
    reca= float(TP/(TP+FN))
    accur= float((TP+TN)/n)
    print(prec,reca,accur)
    
    
#     delta1=[.70,.75,.80,.85,.90,.95]
    #gamma=.05,.06,.07
    #delta1=[.80,.85,.90,.95]
# (for reproducibility)  

# delta1=[.8], gama=[.1], epsilon=[.05]  
# delta1=[.8], gama=[.15], epsilon=[.01]
 
#     delta1=np.arange(1,.79,-.01)
    
#     gama=[.05,.1,.15,.2,.25]
#     epsilon=[.01,.02,.05,.1,.15,.20,.25,.30,.35,.40,.50]

#ADULT ZAFAR =? epsilon=[0.088 ,0.1656, 0.168,  0.211, 0.251 ] 
 
#agarwal=> epsilon=[ 0.071, 0.1271, 0.2437, 0.27 ]
    '''
    gamma2=[[0.0964, 0.1998, 0.1657, 0.24, 0.2326, 0.1467, 0.1391] ,
    [0.1026, 0.1659, 0.14257, 0.1533, 0.2054, 0.1573, 0.1130],
    [0.1255, 0.1104, 0.1123, 0.0666, 0.1460, 0.1409, 0.0956],
    [0.1124, 0.0637, 0.0789, 0.0466, 0.0841, 0.0868, 0.0695]]
    gamma=np.zeros((4,7),dtype=float)
    to=[1,0,2,5,4,3,6]
    k=0
    for i in range(7):
        for j in range(4):
            gamma[j][i]=gamma2[j][to[k]]
        k=k+1
    print(gamma)    
    alpha=[[1,1,1,1,1,1,1]]
    '''
    #gama=[0.0869, 0.0521,0.0782, 0.0608,0.0434, 0.1,0.069,0.0434,0.034]
    epsilon=[.01]
    fi= np.zeros(n,dtype=int) 
#     for delta in delta1:
    #4 gamma=[0.175442,    0.142103, 0.166039,    0.164754,  0.153465,    0.14,  0.104348   ]

    #1 gamma=[0.259147,   0.0730028, 0.210139, 0.0893443, 0.306931, 0.0933333,  0.0347826]
    #gamma=[0.196178,0.126722,   0.179654, 0.140164,     0.153465,   0.133333,  0.0695652]
    '''
    #agarwal
    gamma2=  [[0.175442, 0.196178, 0.255673, 0.259147],
      [0.142103 ,0.126722 ,0.0766758 ,0.0730028],
      [ 0.166039 , 0.179654,  0.208084,  0.210139],
      [0.164754 , 0.140164 , 0.101639 , 0.0893443],
      [0.153465 , 0.153465,  0.287129 , 0.306931],
      [0.14, 0.133333  ,0.0933333 , 0.0933333],
      [0.104348, 0.0695652,0.0434783,0.0347826]]

    '''
    
    #agar
    # gamma2=[[0.175442], [0.142103],[0.166039],[0.164754],[0.153465],[0.14],[0.104348]]
    
    #gamma2=[[0.175442], [0.142103],[0.166039],[0.164754],[0.153465],[0.14],[0.104348]]
    
    
    #bilal
   # gamma2=[[.109868],[.15679],[.124507],[.111475],[.185643],[.140],[.0782608]]

    
    '''
    
     #bilal
    gamma2=[[ 7.73645546,  8.12672176,  8.99908173, 10.30762167, 11.98347107, 13.08539945,
     13.86593205, 14.09550046, 14.02662994, 15.22038567, 15.6795225 ]
    ,[26.09922918, 25.51297362 ,24.15590055, 22.42970362 ,20.56237108 ,19.45499946
     ,17.92422104 ,16.13288459, 14.07013354, 12.202801,   10.98686353]
    ,[ 9.33333333,  9.33333333  ,8.66666667,  8.0      ,   9.33333333 , 9.33333333
      ,9.33333333 , 9.33333333 ,13.33333333 ,11.33333333 ,14.0        ]
    ,[29.7029703  ,29.45544554 ,27.97029703 ,27.47524752 ,27.22772277 ,25.24752475
     ,24.25742574 ,24.25742574 ,21.78217822 ,19.30693069, 18.56435644]
    ,[ 9.42622951 , 9.50819672 ,10.08196721 ,10.24590164  ,9.91803279, 10.08196721
     ,10.40983607 ,10.98360656 ,11.39344262, 11.39344262 ,11.14754098]
    ,[6.08695652 ,4.34782609 ,4.34782609 ,5.2173913,  6.08695652 ,7.82608696
     ,8.69565217 ,6.08695652 ,5.2173913  ,6.95652174 ,7.82608696]
    ,[21.27932865 ,20.9796198  ,20.23462922 ,19.36119198 ,18.5305703,  18.1024148
     ,17.1775989 , 15.81606439, 14.16338414, 13.23000514 ,12.45076212]]
    
    gamma2=[[.07736455,.1198347107,.138659,.140266,.15679],
[.26099,.2056237108,.179242,.140701,.109868],
[.09333,.0933333,.093333,.13333,.140], 
[.297029,.27227,.2425742,.217821,.185643],
[.097029,.099180,.104098,.11393,.111475],
[.0608695652,.0608695,.086956,.052173,.0782608],
[.21212793,0.185220071930125,.17177,.14163,.124507]
]
    gamma=np.transpose(gamma2)
    '''

#     gamma=[[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
# ]
    '''
    alpha=[[1,1,1,1,1,1,1],[.1,1,1,1,1,1,1], [.01,1,1,1,1,1,1],[.001,1,1,1,1,1,1],
           [1,.1,1,1,1,1,1], [1,.01,1,1,1,1,1],[1,.001,1,1,1,1,1],
           [1,1,.1,1,1,1,1], [1,1,.01,1,1,1,1],[1,1,.001,1,1,1,1],
           [1,1,1,.1,1,1,1], [1,1,1,.01,1,1,1],[1,1,1,.001,1,1,1],
           [1,1,1,1,.1,1,1], [1,1,1,1,.01,1,1,],[1,1,1,1,.001,1,1],
           [1,1,1,1,1,.1,1], [1,1,1,1,1,.01,1],[1,1,1,1,1,.001,1],
           [1,1,1,1,1,1,.1], [1,1,1,1,1,1,.01],[1,1,1,1,1,1,.001],
        [.1,.1,1,1,1,1,1],[.01,.01,1,1,1,1,1], [.001,.001,1,1,1,1,1],[.001,.01,1,1,1,1,1],[.001,.1,1,1,1,1,1],
         [.01,.1,1,1,1,1,1] ]
    '''  
     #alpha=[[1,1,1,1,1,1,1], [1,1,1,1,.1,1,1], [1,1,1,1,.01,1,1,],[1,1,1,1,.001,1,1] ]         
    '''
    alpha=[[1,1,1,1,1,1,1], [1,1,1,1,.01,1,1], [.1,1,1,1,.01,1,1,],[1,.1,1,1,.01,1,1],[1,1,.01,1,.01,1,1], [1,1,.1,1,.1,1,1], [.1,1,.01,1,.01,1,1], [.01,1,.1,1,.1,1,1] ]        
    '''       
           #alpha=[90,40,100,10,4,1,10]
    #alpha=[ 9211,  4356, 11678,  1220,   404,   150 ,  115]
    a=0
    '''
    #LP-5
    gamma=[[0.2591466724568451, 0.07392102846648302, 0.21013872238396986, 0.08934426229508197, 0.3069306930693069, 0.09333333333333334, 0.06956521739130435],
[0.24025621539463685, 0.09182736455463728, 0.20106182565507794, 0.10491803278688525, 0.27970297029702973, 0.11333333333333333, 0.06086956521739131],
[0.2213657583324286, 0.10996326905417815, 0.191984928926186, 0.11967213114754098, 0.25, 0.12666666666666668, 0.08695652173913043],
[0.2024753012702204, 0.1283287419651056, 0.18282240109607809, 0.13524590163934427, 0.22277227722772278, 0.14, 0.11304347826086956],
[0.18358484420801216, 0.14646464646464646, 0.17374550436718617, 0.15, 0.19306930693069307, 0.15333333333333332, 0.1391304347826087],
[0.16469438714580392, 0.16483011937557393, 0.16466860763829422, 0.16475409836065574, 0.16584158415841585, 0.16666666666666666, 0.16521739130434782]]
    alpha=[[1,1,1,1,1,1,1]]
    '''

    #agarwal
    '''
    gamma2=    [[0.175442, 0.196178, 0.255673, 0.259147],
                [0.142103,0.126722,0.0766758,0.0730028],
                [0.166039,0.179654,0.208084,0.210139],
                [0.164754,0.140164,0.101639,0.0893443],
                [0.153465,0.153465,0.287129,0.306931],
                [0.14,0.133333,0.0933333,0.0933333],
                [0.104348,0.0695652,0.0434783,0.0347826]]
                
    gamma=np.transpose(gamma2)
    '''
    
    
    '''
    #
    gamma=[[0.143,  0.0594, 0.1227, 0.0663, 0.1336, 0.04 ,  0.026 ],
 [0.1061 ,0.0463 ,0.0911 ,0.0524, 0.1113 ,0.0266, 0.026 ],
 [0.0776 ,0.0525 ,0.0703 ,0.0639, 0.0866, 0.0333, 0.0347],
 [0.0772, 0.0757 ,0.0753, 0.0827, 0.094,  0.0933, 0.0782]] 
    alpha=[[1,1,1,1,1,1,1]]
    '''
    
     #adult LP4 figure varying beta
    '''
    gamma=[[0.02,.02,.02,.02,.02,.02,.02 ],
           [0.025,.025,.025,.025,.025,.025,.025 ],
           [0.05,.05,.05,.05,.05,.05,.05 ],          
        [0.10,.10,.10,.10,.10,.10,.10 ],
 [.12 ,.12 ,.12 ,.12,.12 ,.12 ,.12 ],
 [.14 ,.14 ,.14 ,.14,.14 ,.14 ,.14 ],
 [.16 ,.16 ,.16 ,.16,.16 ,.16 ,.16 ],
 [.18 ,.18 ,.18 ,.18,.18 ,.18 ,.18 ],
 [.20 ,.20 ,.20 ,.20,.20 ,.20 ,.20 ],
           [0.25,.25,.25,.25,.25,.25,.25 ],
           [0.3,.3,.3,.3,.3,.3,.3 ],
           [0.35,.35,.35,.35,.35,.35,.35 ]]
    '''
    gamma=[[.08,.08,.08,.08,.08,.08,.08],
    [.09,.09,.09,.09,.09,.09,.09],
    [.23,.23,.23,.23,.23,.23,.23],
    [.28,.28,.28,.28,.28,.28,.28]]
    alpha=[[1,1,1,1,1,1,1]]
    epsilon=[.01,.02,.03]
    t=0
    #for t in range(gamma.shape[0]):
    #for t in range(28):
    for new in range(12):
        k=0
        for t in range(1):
            for eps in epsilon:
                u1,u2=min_sum_lpca(data,gamma[new],eps,e,alpha[t])
                #######################Disp_impact#######################  
                print("gamma-epsilon-delta",gamma[new],eps)
                accu_all=[]
                DP_all=[]
                precision_all=[]
                recall_all=[]
                ar_all=[]
                acceptance_rate=np.zeros((7,28),dtype=float)
                count=0
                print("<--------------------------------------->")
                print("iteration t",k)
                k=k+1
        #                 for alpha in np.arange(0,1.05,0.05):
        #                     print("alpha: ",alpha)
        #                     for i in range(n):

        #                         z=random()
        #                         if z < alpha:
        #                                fi[i]= u1[i] 

        #                         else:
        #                                fi[i]= r2[i]

                for i in range(n):
                     fi[i] = u1[i]


                for j in range(s):
                    print("sensitive attribute ",(j+1)) 

                    TP=0
                    FP=0
                    FN=0
                    TN=0
                    precision=0
                    recall=0
                    for i in range(n):
                         if data[j][i]== 1 :                        
                            if fi[i]==1 and r[i]==1:
                                TP=TP+1
                            if fi[i]==1 and r[i]==-1:
                                FP=FP+1 
                            if fi[i]==-1 and r[i]==1:
                                FN=FN+1
                            if fi[i]==-1 and r[i]==-1:
                                TN=TN+1    
                    if TP+FP !=0:
                        precision=float(TP/(TP+FP))
                    #print("precision",precision)
                    if TP+FN !=0:    
                        recall=float(TP/(TP+FN))
                    #print("recall",recall)

                    precision_all.append(precision)
                    recall_all.append(recall)
                    #print("TP,FP,TN,FN")
                    #print(TP,FP,TN,FN)

                    a=0
                    b=0
                    acc1=0
                    acc2=0
                    for i in range(n):
                            if data[j][i]== 1 :
                                a=a+1
                                if fi[i]==1:
                                     acc1=acc1+1 

        #                         print("total ,fair accepted, aceeptance rate:")             
                    a1=float(acc1/a)



        #                         print(a)
        #                         print(acc1)
        #                         print(a1)
                    ar_all.append(a1)

                count = count+1
                maxi=max(ar_all)
                mini= min(ar_all)
                DP=float(maxi-mini)
                print("individual acceptance rates")
                print(ar_all)
                print("individul precision")
                print(precision_all)
                print("individual recall")
                print(recall_all)
                print("DP all")
                print(DP)
                f_acc=0
                for i in range(n):
                     if fi[i] == r[i]:
                            f_acc=f_acc+1
                f_acc_l=float((f_acc*100)/n) 

        #######################################################################33   

        #                         print("sensitive attribute ",(j+1)) 





                TP=0
                FP=0
                FN=0
                TN=0
                precision=0
                recall=0
                accu=0
                for i in range(n):
                        if fi[i]==1 and r[i]==1:
                            TP=TP+1
                        if fi[i]==1 and r[i]==-1:
                            FP=FP+1 
                        if fi[i]==-1 and r[i]==1:
                            FN=FN+1
                        if fi[i]==-1 and r[i]==-1:
                            TN=TN+1    

                if TP+FP!=0:
                    precision=float(TP/(TP+FP))
                print("precision all",precision)
                if TP+FN!=0:
                    recall=float(TP/(TP+FN))


                print("recall all",recall)
                accu=float((TP+TN)/(TP+FN+TN+FP))


                print("accuracy all",accu)



                print("TP,FP,TN,FN")
                print(TP,FP,TN,FN)
        #                         print("total ,fair accepted, aceeptance rate:")             
                a1=float(acc1/a)


    print("<--------------------------------------->")
    alpha_weight=np.arange(0,1.05,.05)        
    return accu_all,DP_all,acceptance_rate,alpha_weight

In [19]:
# without accuracy
import time
# import pulp as p 
# from random import *

# Add column names to data set
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 
           'relationship', 'race','sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

# Read in train data
adult_train = pd.read_csv('data/adult_actual/adult_train_data.csv', header=None, names=columns, skipinitialspace=True)

# Drop the fnlwgt column which is useless for later analysis
adult_train = adult_train.drop('fnlwgt', axis=1)

# Read in test data
adult_test = pd.read_csv('data/adult_actual/adult_test_data.csv', header=None, skiprows=1, names=columns, skipinitialspace=True)

# Drop the fnlwgt column which is useless for later analysis
adult_test = adult_test.drop('fnlwgt', axis=1)

# Remove '.' in income column
adult_test['income'] = adult_test['income'].apply(lambda x: '>50k' if x=='>50k.'  else '<=50k')

object_col = adult_train.select_dtypes(include=object).columns.tolist()
for col in object_col:
    adult_train.loc[adult_train[col]=='?', col] = np.nan
    adult_test.loc[adult_test[col]=='?', col] = np.nan

# Perform an mssing assessment in each column of the dataset.
col_missing_pct = adult_train.isna().sum()/adult_train.shape[0]
col_missing_pct.sort_values(ascending=False)

# Remove data entries with missing value
adult_train = adult_train.dropna(axis=0, how='any')
adult_test = adult_test.dropna(axis=0, how='any')


for col in object_col:
    print(adult_train[col].value_counts(dropna=False)/adult_train.shape[0],'\n')
# print(adult_train.head())
# print(adult_test.head())    

adult_train.reset_index(drop=True, inplace=True)
adult_test.reset_index(drop=True, inplace=True)
p=adult_train.shape[0]
q =adult_test.shape[0]
# reducing dimensionality of some very sparse features
for i in range(0,p):
    if adult_train.loc[i,'native-country'] not in ["united-states"] :
               adult_train.loc[i,"native-country"] = "non-united-stated"        
    if adult_train.loc[i,"education"] in ["Preschool", "1st-4th", "5th-6th", "7th-8th"]:
               adult_train.loc[i,"education"] = "prim-middle-school"
    elif adult_train.loc[i,"education"] in ["9th", "10th", "11th", "12th"]:
               adult_train.loc[i,"education"] = "high-school"   
    if adult_train.loc[i,'income'] in [">50k"] :
               adult_train.loc[i,"income"] = 1 
    else: 
               adult_train.loc[i,"income"] = 0         
#reducing dimensionality of some very sparse features
for i in range(0,q):                
    if adult_test.loc[i,'native-country'] not in ["united-states"]:
               adult_test.loc[i,'native-country'] = "non-united-stated"
    if adult_test.loc[i,'education'] in ["Preschool", "1st-4th", "5th-6th", "7th-8th"]:
               adult_test.loc[i,'education'] = "prim-middle-school"
    elif adult_test.loc[i,'education'] in ["9th", "10th", "11th", "12th"]:
               adult_test.loc[i,'education'] = "high-school"   
    if adult_test.loc[i,'income'] in [">50k",">50k."] :
               adult_test.loc[i,"income"] = 1 
    else: 
               adult_test.loc[i,"income"] = 0            
# print(adult_train.head())
# print(adult_test.head())
DATA=pd.concat([adult_train,adult_test],ignore_index=True)
# print(DATA.tail())
m=DATA.shape[1]

dat=DATA.iloc[:,0:m-1]


# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler() # default=(0, 1)
num_col = dat.dtypes[dat.dtypes != 'object'].index
features_log_minmax_transform = pd.DataFrame(data = dat)
features_log_minmax_transform[num_col] = scaler.fit_transform(features_log_minmax_transform[num_col])

display(features_log_minmax_transform.head())

# sens=DATA[['sex','race']]

Data_c = pd.get_dummies(features_log_minmax_transform, columns=['sex','race','workclass','education','marital-status','occupation','relationship','native-country'], prefix =['s','r','work','edu','ms','occ','rls','nc'])
r=DATA.iloc[:,m-1]
print(Data_c)
print(DATA['income'].value_counts())


X_test,Y_test_pred,Y_test,e = adult_svm(Data_c , r)

X_test.reset_index(drop=True, inplace=True)

Y_test.reset_index(drop=True, inplace=True)


sens=X_test[['s_male', 's_female'  ,'r_white', 'r_black', 'r_asian-pac-islander','r_amer-indian-eskimo','r_other']]

sensitive = sens.T

 

private             0.738877
self-emp-not-inc    0.082853
local-gov           0.068530
state-gov           0.042404
self-emp-inc        0.035608
federal-gov         0.031265
without-pay         0.000464
Name: workclass, dtype: float64 

hs-grad         0.326238
some-college    0.221404
bachelors       0.167230
masters         0.053942
assoc-voc       0.043333
11th            0.034746
assoc-acdm      0.033420
10th            0.027187
7th-8th         0.018467
prof-school     0.017970
9th             0.015085
12th            0.012499
doctorate       0.012433
5th-6th         0.009548
1st-4th         0.005006
preschool       0.001492
Name: education, dtype: float64 

married-civ-spouse       0.466315
never-married            0.322459
divorced                 0.139712
separated                0.031132
widowed                  0.027419
married-spouse-absent    0.012267
married-af-spouse        0.000696
Name: marital-status, dtype: float64 

prof-specialty       0.133877
craft-repair         0

age         workclass    education  education-num      marital-status  \
0  0.301370         state-gov    bachelors       0.800000       never-married   
1  0.452055  self-emp-not-inc    bachelors       0.800000  married-civ-spouse   
2  0.287671           private      hs-grad       0.533333            divorced   
3  0.493151           private  high-school       0.400000  married-civ-spouse   
4  0.150685           private    bachelors       0.800000  married-civ-spouse   

          occupation   relationship   race     sex  capital-gain  \
0       adm-clerical  not-in-family  white    male       0.02174   
1    exec-managerial        husband  white    male       0.00000   
2  handlers-cleaners  not-in-family  white    male       0.00000   
3  handlers-cleaners        husband  black    male       0.00000   
4     prof-specialty           wife  black  female       0.00000   

   capital-loss  hours-per-week     native-country  
0           0.0        0.397959      united-states  
1           0.0        0.122449      united-states  
2           0.0        0.397959      united-states  
3           0.0        0.397959      united-states  
4           0.0        0.397959  non-united-stated

            age  education-num  capital-gain  capital-loss  hours-per-week  \
0      0.301370       0.800000      0.021740           0.0        0.397959   
1      0.452055       0.800000      0.000000           0.0        0.122449   
2      0.287671       0.533333      0.000000           0.0        0.397959   
3      0.493151       0.400000      0.000000           0.0        0.397959   
4      0.150685       0.800000      0.000000           0.0        0.397959   
...         ...            ...           ...           ...             ...   
45216  0.219178       0.800000      0.000000           0.0        0.397959   
45217  0.301370       0.800000      0.000000           0.0        0.357143   
45218  0.287671       0.800000      0.000000           0.0        0.500000   
45219  0.369863       0.800000      0.054551           0.0        0.397959   
45220  0.246575       0.800000      0.000000           0.0        0.602041   

       s_female  s_male  r_amer-indian-eskimo  r_asian-pac-isla

In [ ]:
'''
# run it finally to get the precision and recall on set of beta's

accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

'''

In [41]:
# Beta Plot for LP4 to show beta variation from .1 to .2
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)
'''

prec=[[0.9945652173913043, 0.8620689655172413, 0.9828326180257511, 0.7083333333333334, 0.8888888888888888, 0.6666666666666666, 1.0],
[0.9956521739130435, 0.8240740740740741, 0.9759450171821306, 0.6333333333333333, 0.9166666666666666, 0.6666666666666666, 1.0],
[0.9369565217391305, 0.7004608294930875, 0.9090909090909091, 0.47540983606557374, 0.8571428571428571, 0.2857142857142857, 0.8],
[0.8816503800217155, 0.5701149425287356, 0.8508997429305912, 0.3442622950819672, 0.425, 0.1875, 0.45454545454545453],
[0.843289371605896, 0.4975369458128079, 0.8004895960832313, 0.27647058823529413, 0.47368421052631576, 0.14285714285714285, 0.3125],
[0.8153428377460964, 0.46695402298850575, 0.7682012847965739, 0.26666666666666666, 0.46875, 0.16666666666666666, 0.2777777777777778],
[0.7725298588490771, 0.4087256027554535, 0.7147751605995717, 0.24180327868852458, 0.5061728395061729, 0.13333333333333333, 0.2608695652173913],
[0.7328410078192876, 0.3516988062442608, 0.6632408359027064, 0.22295081967213115, 0.5490196078431373, 0.10810810810810811, 0.21428571428571427],
[0.681505609844372, 0.30321592649310875, 0.6094775906365972, 0.1912568306010929, 0.512396694214876, 0.13333333333333333, 0.17647058823529413],
[0.6326403971455166, 0.2664041994750656, 0.5568876926841204, 0.1873536299765808, 0.5319148936170213, 0.1346153846153846, 0.175]]

rec=[[0.06545064377682404, 0.16025641025641027, 0.07773251866938222, 0.10493827160493827, 0.06349206349206349, 0.13333333333333333, 0.13333333333333333],
[0.08190271816881259, 0.19017094017094016, 0.09640190088255261, 0.11728395061728394, 0.0873015873015873, 0.13333333333333333, 0.13333333333333333],
[0.15414878397711015, 0.3247863247863248, 0.17990495587236932, 0.17901234567901234, 0.14285714285714285, 0.13333333333333333, 0.26666666666666666],
[0.290414878397711, 0.5299145299145299, 0.33706720977596744, 0.25925925925925924, 0.1349206349206349, 0.2, 0.3333333333333333],
[0.38876967095851217, 0.6474358974358975, 0.4439918533604888, 0.29012345679012347, 0.21428571428571427, 0.2, 0.3333333333333333],
[0.42954220314735336, 0.6944444444444444, 0.48710115410726407, 0.32098765432098764, 0.23809523809523808, 0.26666666666666666, 0.3333333333333333],
[0.5089413447782547, 0.7606837606837606, 0.56653088934148, 0.36419753086419754, 0.3253968253968254, 0.26666666666666666, 0.4],
[0.6033619456366237, 0.8183760683760684, 0.6571622539035981, 0.41975308641975306, 0.4444444444444444, 0.26666666666666666, 0.4],
[0.6734620886981402, 0.8461538461538461, 0.7247114731839783, 0.43209876543209874, 0.49206349206349204, 0.4, 0.4],
[0.7292560801144492, 0.8675213675213675, 0.7725729803122878, 0.49382716049382713, 0.5952380952380952, 0.4666666666666667, 0.4666666666666667]]

accu=[ 0.7774,0.7813,0.7954,0.8157,0.82442,0.8245,0.8216,0.8146,0.7954,0.7699]





[[0.02,.02,.02,.02,.02,.02,.02 ],
           [0.025,.025,.025,.025,.025,.025,.025 ],
           [0.05,.05,.05,.05,.05,.05,.05 ],          
        [0.10,.10,.10,.10,.10,.10,.10 ],
 [.12 ,.12 ,.12 ,.12,.12 ,.12 ,.12 ],
 [.14 ,.14 ,.14 ,.14,.14 ,.14 ,.14 ],
 [.16 ,.16 ,.16 ,.16,.16 ,.16 ,.16 ],
 [.18 ,.18 ,.18 ,.18,.18 ,.18 ,.18 ],
 [.20 ,.20 ,.20 ,.20,.20 ,.20 ,.20 ],
           [0.25,.25,.25,.25,.25,.25,.25 ],
           [0.3,.3,.3,.3,.3,.3,.3 ],
           [0.35,.35,.35,.35,.35,.35,.35 ]]

.8
.9
.23
.28

0.0347
0.0730

0.0893

0.0933
0.2101

0.2591

0.3069













'''

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
320735.0
discripency is:
None
gamma-epsilon-delta [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05] 0.01
<--------------------------------------->
iteration t 0
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.049940288785148196, 0.049816345270890725, 0.049922932008905636, 0.05, 0.05198019801980198, 0.04666666666666667, 0.043478260869565216]
individul precision
[0.9369565217391305, 0.7004608294930875, 0.9090909090909091, 0.47540983606557374, 0.8571428571428571, 0.2857142857142857, 0.8]
individual recall
[0.15414878397711015, 0.3247863247863248, 0.17990495587236932, 0.17901234567901234, 0.14285714285714285, 0.13333333333333333, 0.26666666666666666]
DP all
0.008501937150236762
precision all 0.8611521418020679
recall all 0.17861519607843138
accuracy all 0.7954595710179111
TP,FP,TN,FN
583 94

Optimal
objective is:
1844540.0
discripency is:
None
gamma-epsilon-delta [0.12, 0.12, 0.12, 0.12, 0.12, 0.12, 0.12] 0.03
<--------------------------------------->
iteration t 2
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.11996525892954077, 0.11983471074380166, 0.11996917280356226, 0.11967213114754098, 0.12128712871287128, 0.12, 0.11304347826086956]
individul precision
[0.8669683257918552, 0.5344827586206896, 0.8322626695217702, 0.2876712328767123, 0.42857142857142855, 0.16666666666666666, 0.38461538461538464]
individual recall
[0.3426323319027182, 0.5961538461538461, 0.3957909029192125, 0.25925925925925924, 0.16666666666666666, 0.2, 0.3333333333333333]
DP all
0.008243650452001719
precision all 0.7602950215119852
recall all 0.3789828431372549
accuracy all 0.821847129063168
TP,FP,TN,FN
1237 390 9913 2027
dimension of data
7 13567
[ 9211  4356

Optimal
objective is:
4097492.0
discripency is:
None
gamma-epsilon-delta [0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18] 0.02
<--------------------------------------->
iteration t 1
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1798936054717186, 0.17998163452708907, 0.17999657475595135, 0.17950819672131146, 0.1806930693069307, 0.18, 0.17391304347826086]
individul precision
[0.7911888955944478, 0.4375, 0.7397716460513797, 0.2557077625570776, 0.4520547945205479, 0.14814814814814814, 0.3]
individual recall
[0.4688841201716738, 0.7329059829059829, 0.5278343516632722, 0.345679012345679, 0.2619047619047619, 0.26666666666666666, 0.4]
DP all
0.006780025828669822
precision all 0.6775911511675543
recall all 0.5067401960784313
accuracy all 0.823321294317093
TP,FP,TN,FN
1654 787 9516 1610
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
O

sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.29996743024644446, 0.29981634527089074, 0.2999657475595136, 0.3, 0.2995049504950495, 0.3, 0.2956521739130435]
individul precision
[0.681505609844372, 0.30321592649310875, 0.6094775906365972, 0.1912568306010929, 0.512396694214876, 0.13333333333333333, 0.17647058823529413]
individual recall
[0.6734620886981402, 0.8461538461538461, 0.7247114731839783, 0.43209876543209874, 0.49206349206349204, 0.4, 0.4]
DP all
0.004347826086956497
precision all 0.560088473826493
recall all 0.6982230392156863
accuracy all 0.7954595710179111
TP,FP,TN,FN
2279 1790 8513 985
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
11106181.0
discripency is:
None
gamma-epsilon-delta [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3] 0.02
<--------------------------------------->
iteration t 1
sensitive attribute  1
sensitive attribute  2
sensitive a

'\n\nprec=[[0.8816, 0.5701, 0.8508, 0.3442, 0.425, 0.1875, 0.4545],\n[0.8669, 0.5344, 0.8322, 0.2876, 0.4285, 0.1666, 0.3846],\n [0.8432, 0.4975, 0.8004, 0.2764, 0.4736, 0.1428, 0.3125],\n[0.8153, 0.4669, 0.7682, 0.2666, 0.4687, 0.1666, 0.2777],\n[0.7911, 0.4375, 0.7397, 0.2557, 0.4520, 0.1481, 0.3],\n[0.7725, 0.4087, 0.7147, 0.2418, 0.5061, 0.1333, 0.2608]]\n\n      \nrec=[[0.2904, 0.5299, 0.3370, 0.2592, 0.1349, 0.2, 0.3333],\n[0.3426, 0.5961, 0.3957, 0.2592, 0.1666, 0.2, 0.3333],\n [0.3887, 0.6474, 0.4439, 0.2901, 0.2142, 0.2, 0.3333],    \n[0.4295, 0.6944, 0.4871, 0.3209, 0.2380, 0.2666, 0.3333],\n[0.4688, 0.7329, 0.5278, 0.3456, 0.2619, 0.2666, 0.4],\n[0.5089, 0.7606, 0.5665, 0.3641, 0.3253, 0.2666, 0.4] ]  \n\naccuracy=[0.8157,8218,0.8244,0.8245,0.8233,0.8216]\n\n\n'

In [43]:
# Beta Plot for LP4 to show beta variation from .1 to .2
'''



 
 '''
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
6598360.0
discripency is:
None
gamma-epsilon-delta [0.23, 0.23, 0.23, 0.23, 0.23, 0.23, 0.23] 0.01
<--------------------------------------->
iteration t 0
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.22994246010205188, 0.2297979797979798, 0.229919506764857, 0.22950819672131148, 0.23267326732673269, 0.22666666666666666, 0.22608695652173913]
individul precision
[0.7488196411709159, 0.37362637362637363, 0.6830540037243947, 0.23214285714285715, 0.5425531914893617, 0.11764705882352941, 0.23076923076923078]
individual recall
[0.567238912732475, 0.7991452991452992, 0.6225390359809911, 0.4012345679012346, 0.40476190476190477, 0.26666666666666666, 0.4]
DP all
0.006586310804993556
precision all 0.6284065405578712
recall all 0.6004901960784313
accuracy all 0.8184565489791406
TP,FP,TN,FN


IndexError: list index out of range

In [35]:
# padala final
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

prec=[
[0.7782, 0.5584, 0.7736, 0.4494, 0.7894, 0.2222, 0.4],
[0.8174, 0.5089, 0.8022, 0.3717, 0.7058, 0.2272, 0.4166],
    [0.8700, 0.5146, 0.8321, 0.2573, 0.3965, 0.25, 0.4],
[0.9277, 0.5705, 0.8555, 0.2689, 0.4358, 0.3333, 0.4]]
recall=[
[0.5121, 0.5, 0.5081, 0.4938, 0.5952, 0.5333, 0.4],
    [0.4467, 0.4850, 0.4531, 0.4382, 0.4761, 0.3333, 0.3333],
    [0.3161, 0.6004, 0.3703, 0.2716, 0.1825, 0.2, 0.2666],
    [0.2020, 0.5961, 0.2674, 0.1975, 0.1349, 0.2, 0.2666]]

DP=[0.1438,0.1080,0.0635,0.0522]



sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

IndexError: index 4 is out of bounds for axis 0 with size 4

In [28]:
#Overlapping paper final
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

In [25]:
#LP-5
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

In [51]:
#final agar1
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

precision all 0.7324003392705682
recall all 0.5291053921568627
accuracy all 0.8402004864745338
TP,FP,TN,FN
1727 631 9672 1537
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3432702.0
discripency is:
None
gamma-epsilon-delta [0.196178  0.126722  0.179654  0.140164  0.153465  0.133333  0.0695652] 0.01
<--------------------------------------->
iteration t 2
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.19606991640429922, 0.12672176308539945, 0.17956841924987155, 0.14016393442622951, 0.15841584158415842, 0.12666666666666668, 0.06086956521739131]
individul precision
[0.782392026578073, 0.572463768115942, 0.7439198855507868, 0.5730994152046783, 0.90625, 0.42105263157894735, 0.7142857142857143]
individual recall
[0.5053648068669528, 0.6752136752136753, 0.5295315682281059, 0.6049382716049383, 0.46031746031

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
5172246.0
discripency is:
None
gamma-epsilon-delta [0.259147  0.0730028 0.210139  0.0893443 0.306931  0.0933333 0.0347826] 0.01
<--------------------------------------->
iteration t 2
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.2591466724568451, 0.07346189164370982, 0.21013872238396986, 0.08934426229508197, 0.31435643564356436, 0.08666666666666667, 0.034782608695652174]
individul precision
[0.7293674067867616, 0.725, 0.7334963325183375, 0.7155963302752294, 0.6771653543307087, 0.46153846153846156, 0.75]
individual recall
[0.6226752503576538, 0.49572649572649574, 0.6109979633401222, 0.48148148148148145, 0.6825396825396826, 0.4, 0.2]
DP all
0.27957382694791216
precision all 0.7288511267085335
recall all 0.6044730392156863
accuracy all 0.8507407680400972
TP,FP,TN,FN
1973 734 9569

In [55]:
#final bilal1
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3651415.0
discripency is:
None
gamma-epsilon-delta [0.11983471 0.20562371 0.0933333  0.27227    0.09918    0.0608695
 0.18522007] 0.01
<--------------------------------------->
iteration t 1
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.20562371078058841, 0.11960514233241507, 0.18513444082890906, 0.09836065573770492, 0.28217821782178215, 0.08666666666666667, 0.05217391304347826]
individul precision
[0.7713833157338965, 0.5969289827255279, 0.7409805735430157, 0.65, 0.7105263157894737, 0.5384615384615384, 0.6666666666666666]
individual recall
[0.5225321888412017, 0.6645299145299145, 0.5437881873727087, 0.48148148148148145, 0.6428571428571429, 0.4666666666666667, 0.26666666666666666]
DP all
0.2300043047783039
precision all 0.7337474120082815
recall all 0.5428921568627451
accuracy 

sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.14059276951471067, 0.14003673094582186, 0.14163384141120056, 0.11311475409836065, 0.21534653465346534, 0.12666666666666668, 0.06086956521739131]
individul precision
[0.8432432432432433, 0.5360655737704918, 0.7817412333736397, 0.5289855072463768, 0.47126436781609193, 0.3684210526315789, 0.7142857142857143]
individual recall
[0.3905579399141631, 0.6987179487179487, 0.43890020366598775, 0.4506172839506173, 0.3253968253968254, 0.4666666666666667, 0.3333333333333333]
DP all
0.15447696943607403
precision all 0.7448818897637796
recall all 0.43474264705882354
accuracy all 0.8281860396550453
TP,FP,TN,FN
1419 486 9817 1845
[0.140701, 0.140266, 0.14163, 0.11393, 0.217821, 0.13333, 0.052173]
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
2116480.0
discripency is:
None
gamma-epsilon-delta [0.140266 0.140701 0.1

precision all 0.728883638511518
recall all 0.37806372549019607
accuracy all 0.8165401341490381
TP,FP,TN,FN
1234 459 9844 2030
<--------------------------------------->


In [89]:
#agar1
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3384025.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 5
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15099009900990099, 0.14, 0.11304347826086956]
individul precision
[0.7981424148606812, 0.47334410339256866, 0.7689530685920578, 0.3, 0.3770491803278688, 0.19047619047619047, 0.3076923076923077]
individual recall
[0.46101573676680974, 0.6260683760683761, 0.5061099796334012, 0.37037037037037035, 0.18253968253968253, 0.26666666666666666, 0.26666666666666666]
DP all
0.06229036171307463
precision all 0.7081468218442256
recall all 0.4846813725490196
accuracy all 0.8279649148669566
TP,

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3660290.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 13
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15346534653465346, 0.14, 0.10434782608695652]
individul precision
[0.8012383900928792, 0.5105008077544426, 0.7663744198040227, 0.375, 0.6451612903225806, 0.19047619047619047, 0.4166666666666667]
individual recall
[0.46280400572246067, 0.6752136752136753, 0.5044127630685675, 0.46296296296296297, 0.31746031746031744, 0.26666666666666666, 0.3333333333333333]
DP all
0.07098601388698768
precision all 0.720680393912265
recall all 0.49325980392156865
accuracy all 0.8320925775779465
TP

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3670086.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 21
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15346534653465346, 0.14, 0.10434782608695652]
individul precision
[0.8018575851393189, 0.5105008077544426, 0.7668901495616297, 0.375, 0.6451612903225806, 0.19047619047619047, 0.4166666666666667]
individual recall
[0.46316165951359084, 0.6752136752136753, 0.5047522063815343, 0.46296296296296297, 0.31746031746031744, 0.26666666666666666, 0.3333333333333333]
DP all
0.07098601388698768
precision all 0.7211280214861235
recall all 0.49356617647058826
accuracy all 0.8322399941033389
T

In [93]:
#agar2
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

precision all 0.7179946284691137
recall all 0.49142156862745096
accuracy all 0.8312080784255915
TP,FP,TN,FN
1604 630 9673 1660
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
2859605.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 5
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15346534653465346, 0.14, 0.10434782608695652]
individul precision
[0.7962848297213623, 0.5121163166397416, 0.7586384734399175, 0.47, 0.3709677419354839, 0.38095238095238093, 0.5833333333333334]
individual recall
[0.45994277539341916, 0.6773504273504274, 0.49932111337406654, 0.5802469135802469, 0.18253968253968253, 0.533333333333

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3012845.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 13
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15346534653465346, 0.14, 0.10434782608695652]
individul precision
[0.8006191950464396, 0.5363489499192245, 0.7524497163486333, 0.5, 0.8064516129032258, 0.38095238095238093, 0.6666666666666666]
individual recall
[0.4624463519313305, 0.7094017094017094, 0.4952477936184657, 0.6172839506172839, 0.3968253968253968, 0.5333333333333333, 0.5333333333333333]
DP all
0.07098601388698768
precision all 0.7273948075201433
recall all 0.49785539215686275
accuracy all 0.834303825458834
TP,FP,TN

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3106310.0
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.1 1
<--------------------------------------->
iteration t 21
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1753338399739442, 0.1421028466483012, 0.1660387052577496, 0.16393442622950818, 0.15099009900990099, 0.14, 0.11304347826086956]
individul precision
[0.7962848297213623, 0.5218093699515347, 0.7539969056214544, 0.505, 0.4918032786885246, 0.38095238095238093, 0.6153846153846154]
individual recall
[0.45994277539341916, 0.6901709401709402, 0.49626612355736593, 0.6234567901234568, 0.23809523809523808, 0.5333333333333333, 0.5333333333333333]
DP all
0.06229036171307463
precision all 0.7202327663384065
recall all 0.49295343137254904
accuracy all 0.831945161052554
TP,

In [24]:
#bilal1>
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
1950017.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 5
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.11898816632287483, 0.15656565656565657, 0.12442199006679226, 0.12459016393442623, 0.2871287128712871, 0.24, 0.1826086956521739]
individul precision
[0.8640510948905109, 0.4413489736070381, 0.8155540261527874, 0.21710526315789475, 0.1896551724137931, 0.08333333333333333, 0.23809523809523808]
individual recall
[0.3386981402002861, 0.6431623931623932, 0.40224032586558045, 0.2037037037037037, 0.1746031746031746, 0.2, 0.3333333333333333]
DP all
0.16814054654841226
precision all 0.7019122609673791
recall all 0.38235294117647056
accuracy all 0.81233876317535

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
2308570.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 13
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.10976006948214091, 0.15656565656565657, 0.12442199006679226, 0.11065573770491803, 0.18316831683168316, 0.14666666666666667, 0.0782608695652174]
individul precision
[0.8724035608308606, 0.48826979472140764, 0.7838953888506538, 0.2814814814814815, 0.4189189189189189, 0.13636363636363635, 0.4444444444444444]
individual recall
[0.315450643776824, 0.7115384615384616, 0.38662593346911067, 0.2345679012345679, 0.24603174603174602, 0.2, 0.26666666666666666]
DP all
0.10490744726646577
precision all 0.7176609568812758
recall all 0.37224264705882354
accuracy all

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
2322070.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 21
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.10976006948214091, 0.15656565656565657, 0.12442199006679226, 0.11065573770491803, 0.18316831683168316, 0.14666666666666667, 0.0782608695652174]
individul precision
[0.8714144411473789, 0.48826979472140764, 0.7838953888506538, 0.2814814814814815, 0.40540540540540543, 0.13636363636363635, 0.4444444444444444]
individual recall
[0.31509298998569385, 0.7115384615384616, 0.38662593346911067, 0.2345679012345679, 0.23809523809523808, 0.2, 0.26666666666666666]
DP all
0.10490744726646577
precision all 0.7170702894270525
recall all 0.37193627450980393
accuracy 

In [22]:
#bilal2>
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
1493108.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 5
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.10976006948214091, 0.15656565656565657, 0.12442199006679226, 0.11147540983606558, 0.18316831683168316, 0.14, 0.0782608695652174]
individul precision
[0.8674579624134521, 0.48533724340175954, 0.7680660701995871, 0.47058823529411764, 0.24324324324324326, 0.23809523809523808, 0.5555555555555556]
individual recall
[0.3136623748211731, 0.7072649572649573, 0.3788187372708758, 0.3950617283950617, 0.14285714285714285, 0.3333333333333333, 0.3333333333333333]
DP all
0.10490744726646577
precision all 0.713526284701713
recall all 0.3700980392156863
accuracy all 0

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
1676481.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 13
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.10976006948214091, 0.15656565656565657, 0.12442199006679226, 0.11065573770491803, 0.18811881188118812, 0.14, 0.06956521739130435]
individul precision
[0.8763600395647874, 0.5087976539589443, 0.7639366827253957, 0.5111111111111111, 0.5789473684210527, 0.23809523809523808, 0.625]
individual recall
[0.3168812589413448, 0.7414529914529915, 0.37678207739307534, 0.42592592592592593, 0.3492063492063492, 0.3333333333333333, 0.3333333333333333]
DP all
0.11855359448988377
precision all 0.7282929710572947
recall all 0.37775735294117646
accuracy all 0.8163927176

precision all 0.722386296515062
recall all 0.3746936274509804
accuracy all 0.8149185523697207
TP,FP,TN,FN
1223 470 9833 2041
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
1795966.0
discripency is:
None
gamma-epsilon-delta [0.109868  0.15679   0.124507  0.111475  0.185643  0.14      0.0782608] 0.1 1
<--------------------------------------->
iteration t 21
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.10976006948214091, 0.15656565656565657, 0.12442199006679226, 0.11065573770491803, 0.18316831683168316, 0.14, 0.08695652173913043]
individul precision
[0.8704253214638972, 0.5029325513196481, 0.7646249139710943, 0.5111111111111111, 0.44594594594594594, 0.23809523809523808, 0.5]
individual recall
[0.3147353361945637, 0.7329059829059829, 0.3771215207060421, 0.42592592592592593, 0.2619047619047619, 0.33333

In [60]:
#agar test
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Infeasible
objective is:
7831930.000000004
discripency is:
None
gamma-epsilon-delta [0.175442 0.142103 0.166039 0.164754 0.153465 0.14     0.104348] 0.01
<--------------------------------------->
iteration t 5
sensitive attribute  1
sensitive attribute  2
sensitive attribute  3
sensitive attribute  4
sensitive attribute  5
sensitive attribute  6
sensitive attribute  7
individual acceptance rates
[0.1068287916621431, 0.1753902662993572, 0.11440315122452474, 0.16393442622950818, 0.17574257425742573, 0.18, 0.991304347826087]
individul precision
[0.8323170731707317, 0.4620418848167539, 0.7559880239520959, 0.47, 0.6338028169014085, 0.2962962962962963, 0.13157894736842105]
individual recall
[0.2929184549356223, 0.7542735042735043, 0.3428377460964019, 0.5802469135802469, 0.35714285714285715, 0.5333333333333333, 1.0]
DP all
0.8844755561639439
precision all 0.6704805491990846
recall all 0.3590686274509804
accuracy all 0.8033463551264096
TP,FP,TN,FN
11

In [72]:
accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e)


sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
9211
2796
0.30355010313755293
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
4356
468
0.10743801652892562
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
11678
2946
0.252269224182223
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
1220
162
0.13278688524590163
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
404
126
0.3118811881188119
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
150
15
0.1
sensitive attribute  7
ACTUAL----------total ,accepted, aceeptance rate:
115
15
0.13043478260869565
data acceptance rates
[0.30355010313755293, 0.10743801652892562, 0.252269224182223, 0.13278688524590163, 0.3118811881188119, 0.1, 0.13043478260869565]
data DP
0.21188118811881188
sensitive attribute  1
prec reca accuracy for each sens
0.7297863426895685 0.623032904148784 0.815546629030507
SVM----------tota

[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
3088353.0
discripency is:
None
gamma-epsilon-delta [0.175442, 0.142103, 0.166039, 0.164754, 0.153465, 0.14, 0.104348] 0.01 1
<--------------------------------------->
sensitive attribute  1
precision 0.8293564714389009
recall 0.4102288984263233
TP,FP,TN,FN
1147 236 6179 1649
sensitive attribute  2
precision 0.4877675840978593
recall 0.6816239316239316
TP,FP,TN,FN
319 335 3553 149
sensitive attribute  3
precision 0.776255707762557
recall 0.461642905634759
TP,FP,TN,FN
1360 392 8340 1586
sensitive attribute  4
precision 0.3551912568306011
recall 0.4012345679012346
TP,FP,TN,FN
65 118 940 97
sensitive attribute  5
precision 0.5081967213114754
recall 0.24603174603174602
TP,FP,TN,FN
31 30 248 95
sensitive attribute  6
precision 0.17391304347826086
recall 0.26666666666666666
TP,FP,TN,FN
4 19 116 11
sensitive attribute  7
precision 0.3333333333333333
recall 0.4
TP,FP,TN,FN
6 12 88 9
acceptance rates
[0.1501465638909999, 0.1501377

precision 0.7421383647798742
recall 0.5042735042735043
TP,FP,TN,FN
236 82 3806 232
sensitive attribute  3
precision 0.732681336593317
recall 0.6103190767141887
TP,FP,TN,FN
1798 656 8076 1148
sensitive attribute  4
precision 0.7339449541284404
recall 0.49382716049382713
TP,FP,TN,FN
80 29 1029 82
sensitive attribute  5
precision 0.7258064516129032
recall 0.7142857142857143
TP,FP,TN,FN
90 34 244 36
sensitive attribute  6
precision 0.5
recall 0.4666666666666667
TP,FP,TN,FN
7 7 128 8
sensitive attribute  7
precision 0.75
recall 0.2
TP,FP,TN,FN
3 1 99 12
acceptance rates
[0.2591466724568451, 0.07300275482093664, 0.21013872238396986, 0.08934426229508197, 0.3069306930693069, 0.09333333333333334, 0.034782608695652174]
DP
0.27214808437365473
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
6240475.0
discripency is:
None
gamma-epsilon-delta [0.175442, 0.142103, 0.166039, 0.164754, 0.153465, 0.14, 0.104348] 0.01 1
<--------------------------------------->

precision 0.7272727272727273
recall 0.5333333333333333
TP,FP,TN,FN
8 3 97 7
acceptance rates
[0.267397676690913, 0.11891643709825528, 0.2281212536393218, 0.1319672131147541, 0.3069306930693069, 0.14, 0.09565217391304348]
DP
0.21127851915626344
dimension of data
7 13567
[ 9211  4356 11678  1220   404   150   115]
Optimal
objective is:
7826668.0
discripency is:
None
gamma-epsilon-delta [0.175442, 0.142103, 0.166039, 0.164754, 0.153465, 0.14, 0.104348] 0.01 1
<--------------------------------------->
sensitive attribute  1
precision 0.7163120567375887
recall 0.6502145922746781
TP,FP,TN,FN
1818 720 5695 978
sensitive attribute  2
precision 0.4909090909090909
recall 0.75
TP,FP,TN,FN
351 364 3524 117
sensitive attribute  3
precision 0.6854558107167711
recall 0.6687033265444671
TP,FP,TN,FN
1970 904 7828 976
sensitive attribute  4
precision 0.4811320754716981
recall 0.6296296296296297
TP,FP,TN,FN
102 110 948 60
sensitive attribute  5
precision 0.6504065040650406
recall 0.6349206349206349
TP,FP