In [12]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
sns.set(style="darkgrid")
from time import time

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

# Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.metrics import fbeta_score
from sklearn.metrics import accuracy_score
# Import the three supervised learning models from sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA    

# Pretty display for notebooks
%matplotlib inline

In [16]:
#SVM 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
%pylab inline
from random import *
from subprocess import check_output
def Bank_svm(X,Y):
    #Split data into training and test datasets (training will be based on 70% of data)
    from sklearn.model_selection import train_test_split
    
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0,shuffle=True) 
    #test_size: if integer, number of examples into test dataset; if between 0.0 and 1.0, means proportion
    print('There are {} samples in the training set and {} samples in the test set'.format(X_train.shape[0], X_test.shape[0]))

    
    #Scaling data
    #from sklearn.preprocessing import StandardScaler
    
    from sklearn.model_selection import cross_val_score

    #sc = StandardScaler(with_mean=False)
    
    
    #sc.fit(X_train)
    #X_train_std = sc.transform(X_train)
    #X_test_std = sc.transform(X_test)

    #X_train_std and X_test_std are the scaled datasets to be used in algorithms

    #Applying SVC (Support Vector Classification)
    from sklearn.svm import SVC
    svm = SVC(kernel='rbf', random_state=0, gamma=.001, C=1.0,probability=True)
    svm.fit(X_train, Y_train)
    print('The accuracy of the SVM classifier on training data is {:.2f}'.format(svm.score(X_train, Y_train)))
    print('The accuracy of the SVM classifier on test data is {:.2f}'.format(svm.score(X_test, Y_test)))
    print('####Train prediction Label###############################################')
    Y_train_pred=svm.predict(X_train)
    #print(y_1)
    Y_test_pred=svm.predict(X_test)

    print('####Actual Train Label###############################################')
    e=svm.predict_proba(X_test)

    print(e)
    print(Y_test_pred)
    print('####Change to colors###############################################')
        
    
    return X_test,Y_test_pred,Y_test,e

Populating the interactive namespace from numpy and matplotlib


/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['shuffle', 'choice', 'triangular', 'sample', 'randint', 'uniform', 'seed', 'random', 'e', 'time']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [ ]:
#without accuracy ---> 2
def main(datax, y_test, y_test_pred,e): 
        
    n=datax.shape[1]
    s=datax.shape[0]    
    data = np.zeros((s, n), dtype = int)
    
    r = np.zeros(n, dtype = int) 
    
    for i in range(n):
        if int(y_test.iloc[i])==1 :
            r[i]=1
        else :
            r[i]= -1  
    
    r2 = np.zeros(n, dtype = int) 
    for i in range(n):
        if int(y_test_pred[i])==1 :
            r2[i]=1
        else :
            r2[i]= -1          
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        for i in range(n):
                data[j][i]= datax.iloc[j,i]
                if data[j][i]== 1 :
                    a=a+1
                    if r[i]==1:
                         acc1=acc1+1 

        print("ACTUAL----------total ,accepted, aceeptance rate:")             
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP)
    
    ar=[]
    
    for j in range(s):
        print("sensitive attribute ",(j+1)) 
        a=0
        b=0
        acc1=0
        acc2=0
        prec=0
        reca=0
        accur=0
        FP=0
        FN=0
        TP=0
        TN=0
        for i in range(n):
             if data[j][i]== 1 :
                    a=a+1
                    if r2[i]==1:
                        acc1=acc1+1 
                        if r[i]==1:
                            TP=TP+1
                        else:
                             FP=FP+1                
                    else:
                        if r[i]==1:
                            FN=FN+1
                        else:
                            TN=TN+1    
        
        print("prec reca accuracy for each sens") 
        prec= float(TP/(TP+FP))
        reca= float(TP/(TP+FN))
        accur= float((TP+TN)/a)
        print(prec,reca,accur)
        
        
        print("SVM----------total , accepted, aceeptance rate:")             
        
        a1=float(acc1/a)
        print(a)
        
        print(acc1)
        print(a1)
        ar.append(a1)
        
    maxi= max(ar)
    mini= min(ar)
    DP=float(maxi-mini)
    print("data acceptance rates")
    print(ar)
    print("data DP")
    print(DP) 
    
    print("SVM accuracy--------------------------")
    prec=0
    reca=0
    accur=0
    FP=0
    FN=0
    TP=0
    TN=0
    for i in range(n):
            if r2[i]==1:
                acc1=acc1+1 
                if r[i]==1:
                    TP=TP+1
                else:
                     FP=FP+1                
            else:
                if r[i]==1:
                     FN=FN+1
                else:
                     TN=TN+1    

        
    prec= float(TP/(TP+FP))
    reca= float(TP/(TP+FN))
    accur= float((TP+TN)/n)
    print(prec,reca,accur)
    
    epsilon=[.01]
    fi= np.zeros(n,dtype=int) 

    
    #alpha=[[1,.1,1,1,1,1],[1,1,1,1,.01,1],[1,1,1,1,1,.001]] 
    alpha=[[1,1,1,1,1,1]]
    
    1st
    gamma=[[0.2970639032815199, 0.06707420614705382, 0.07105054247155332, 0.10202881505439576, 0.056, 0.043478260869565216],
[0.25734024179620035, 0.06911190354898965, 0.0723736438211167, 0.09732431637753602, 0.06036363636363636, 0.08695652173913043],
[0.21243523316062177, 0.07123450500933945, 0.07369674517068008, 0.09232578653337253, 0.06472727272727273, 0.08695652173913043],
[0.16753022452504318, 0.07327220241127526, 0.07488753638528711, 0.08732725668920906, 0.06909090909090909, 0.08695652173913043],
[0.12435233160621761, 0.07539480387162506, 0.07621063773485048, 0.0826227580123493, 0.07345454545454545, 0.08695652173913043],
[0.08635578583765112, 0.07751740533197486, 0.07753373908441387, 0.07880035283740076, 0.07781818181818181, 0.08695652173913043]]
        '''
    gamma=[[0.2970639032815199, 0.06707420614705382, 0.07105054247155332, 0.10202881505439576, 0.056, 0.043478260869565216],
[0.26252158894645944, 0.07361181864493123, 0.07687218840963218, 0.10173478388709203, 0.06545454545454546, 0.08695652173913043],
[0.22279792746113988, 0.08023433520122261, 0.08269383434771103, 0.1014407527197883, 0.07418181818181818, 0.08695652173913043],
[0.18134715025906736, 0.08685685175751401, 0.08851548028578989, 0.10085269038518083, 0.0829090909090909, 0.08695652173913043],
[0.1381692573402418, 0.09322465613856343, 0.09407250595395607, 0.09997059688326963, 0.09090909090909091, 0.08695652173913043],
[0.1381692573402418, 0.0999320767532688, 0.09989415189203493, 0.10673331373125551, 0.09963636363636363, 0.08695652173913043]]
    '''
    
    '''
    gamma2=[[0.2970639033,0.2158894646,.127806563,.0967184801,.1070811744],
[0.05815928,0.0556970623,0.0562913907,0.0560366786,.0578196638],
[0.0631119344,0.0599364911,0.0571579783,0.0553056364,.0571579783],
[0.0911496619,0.0782122905,0.072037636,0.0682152308,.0743898853],
[0.0501818182,.0443636364 ,.0429090909,.0472727273,.0414545455],
[0.0434782609,0.0434782609,0.0434782609,.0434782609,.0434782609]]


    gamma=np.transpose(gamma2)
    

    
    alpha=[[1,1,1,1,1,1],[.1,1,1,1,1,1], [.01,1,1,1,1,1],[.001,1,1,1,1,1],
           [1,.1,1,1,1,1], [1,.01,1,1,1,1],[1,.001,1,1,1,1],
           [1,1,.1,1,1,1], [1,1,.01,1,1,1],[1,1,.001,1,1,1],
           [1,1,1,.1,1,1], [1,1,1,.01,1,1],[1,1,1,.001,1,1],
           [1,1,1,1,.1,1], [1,1,1,1,.01,1],[1,1,1,1,.001,1],
           [1,1,1,1,1,.1], [1,1,1,1,1,.01],[1,1,1,1,1,.001],
        [.1,.1,1,1,1,1],[.01,.01,1,1,1,1], [.001,.001,1,1,1,1],[.001,.01,1,1,1,1],[.001,.1,1,1,1,1],
         [.01,.1,1,1,1,1] ]
    '''
         
    a=0
    print(alpha)
    
    '''
    #agarwal 1 15 25
     alpha=[[1,1,1,1,1,1],[1,1,1,1,.01,1],  [.01,.1,1,1,1,1] ] 
    gamma2=   [[ 0.074266,0.0725389,0.0794473,0.0777202,0.0673575],
[0.051367,0.051367,0.0517915,0.0524707,0.0533197],
[0.0497486,0.0497486,0.0493517,0.0501455,0.0504102],
[0.0629227,0.0649809,0.0729197,0.0738018,0.0743899],
[0.0407273,0.0349091,0.0254545,0.024,0.024],
[0.0869565,0.0869565,0,0,0]]
    
                
    gamma=np.transpose(gamma2)
    '''
    prec_all=np.zeros((6,7),dtype=float)
    rec_all=np.zeros((6,7),dtype=float)
    acc_rate=np.zeros((6,7),dtype=float)
    
    t=0
    for new in range(6):
        for k in range(1):
            for eps in epsilon:
                u1,u2=min_sum_lpcna(data,gamma[new],eps,e,alpha[k],r2)
                #######################Disp_impact#######################  
                print("gamma-epsilon-delta",gamma[new],eps)
                accu_all=[]
                DP_all=[]
                precision_all=[]
                recall_all=[]
                ar_all=[]
                acceptance_rate=np.zeros((7,28),dtype=float)
                count=0
                print("<--------------------------------------->")
                print("iteration t",t)


                for i in range(n):
                     fi[i] = u1[i]


                for j in range(s):
                    print("sensitive attribute ",(j+1)) 

                    TP=0
                    FP=0
                    FN=0
                    TN=0
                    precision=0
                    recall=0
                    for i in range(n):
                         if data[j][i]== 1 :                        
                            if fi[i]==1 and r[i]==1:
                                TP=TP+1
                            if fi[i]==1 and r[i]==-1:
                                FP=FP+1 
                            if fi[i]==-1 and r[i]==1:
                                FN=FN+1
                            if fi[i]==-1 and r[i]==-1:
                                TN=TN+1    
                    if TP+FP !=0:
                        precision=float(TP/(TP+FP))
                    #print("precision",precision)
                    if TP+FN !=0:    
                        recall=float(TP/(TP+FN))
                    #print("recall",recall)

                    precision_all.append(precision)
                    recall_all.append(recall)
                    #print("TP,FP,TN,FN")
                    #print(TP,FP,TN,FN)

                    a=0
                    b=0
                    acc1=0
                    acc2=0
                    for i in range(n):
                            if data[j][i]== 1 :
                                a=a+1
                                if fi[i]==1:
                                     acc1=acc1+1 

        #                         print("total ,fair accepted, aceeptance rate:")             
                    a1=float(acc1/a)



        #                         print(a)
        #                         print(acc1)
        #                         print(a1)
                    ar_all.append(a1)
                    prec_all[t][j]=precision
                    rec_all[t][j]=recall
                    acc_rate[t][j]=a1
                t=t+1
                count = count+1
                maxi=max(ar_all)
                mini= min(ar_all)
                DP=float(maxi-mini)
                print("individual acceptance rates")
                print(ar_all)
                print("individul precision")
                print(precision_all)
                print("individual recall")
                print(recall_all)
                print("DP all")
                print(DP)
                f_acc=0
                for i in range(n):
                     if fi[i] == r[i]:
                            f_acc=f_acc+1
                f_acc_l=float((f_acc*100)/n) 

        #######################################################################33   

        #                         print("sensitive attribute ",(j+1)) 





                TP=0
                FP=0
                FN=0
                TN=0
                precision=0
                recall=0
                accu=0
                for i in range(n):
                        if fi[i]==1 and r[i]==1:
                            TP=TP+1
                        if fi[i]==1 and r[i]==-1:
                            FP=FP+1 
                        if fi[i]==-1 and r[i]==1:
                            FN=FN+1
                        if fi[i]==-1 and r[i]==-1:
                            TN=TN+1    

                if TP+FP!=0:
                    precision=float(TP/(TP+FP))
                print("precision all",precision)
                if TP+FN!=0:
                    recall=float(TP/(TP+FN))


                print("recall all",recall)
                accu=float((TP+TN)/(TP+FN+TN+FP))


                print("accuracy all",accu)



                print("TP,FP,TN,FN")
                print(TP,FP,TN,FN)
        #                         print("total ,fair accepted, aceeptance rate:")             
                a1=float(acc1/a)


    print("<--------------------------------------->")
    alpha_weight=np.arange(0,1.2,.2)        
    return accu_all,DP_all,acc_rate,alpha_weight,prec_all,rec_all

In [19]:

#NG
import time
import pulp as p 
def min_sum_lpcna(data1,beta,eps,e,alpha,y):
    import pulp as p 
    import math
    
    m=data1.shape[0]
    n=data1.shape[1]
    print('dimension of data')
    print(m,n)
    
    ################ sorted result
    h1=[]
    h2=[]
    h3=[]
    h4=[]
    h5=[]
    h6=[]
   
    key1=[]
    key2=[]
    key3=[]
    key4=[]
    key5=[]
    key6=[]
   
    cost=np.zeros(n,dtype=int)
    data2=np.zeros((m,n),dtype=int)
    for i in range(n):
        if data1[0][i]==1:            

            h1.append(e[i][1])
            key1.append(i)

        elif data1[1][i]==1:
            h2.append(e[i][1])
            key2.append(i)
            
        if data1[2][i]==1:
            h3.append(e[i][1])
            key3.append(i)
            
        elif data1[3][i]==1:
            h4.append(e[i][1])
            key4.append(i)
        elif data1[4][i]==1:
            h5.append(e[i][1])
            key5.append(i)
        elif data1[5][i]==1:
            h6.append(e[i][1])
            key6.append(i)
        elif data1[6][i]==1:
            h7.append(e[i][1])
            key7.append(i)
#print(hc)
#     print(key1)
    
    for i in range(1,len(h1)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h1[j-1]<h1[j]:
                index=j
                var=h1[j]
                h1[j]=h1[j-1]
                h1[j-1]=var

                var2=key1[j]
                key1[j]=key1[j-1]
                key1[j-1]=var2
            else:
                break
    

    for i in range(1,len(h2)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h2[j-1]<h2[j]:
                index=j
                var=h2[j]
                h2[j]=h2[j-1]
                h2[j-1]=var

                var2=key2[j]
                key2[j]=key2[j-1]
                key2[j-1]=var2
            else:
                break
    for i in range(1,len(h3)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h3[j-1]<h3[j]:
                index=j
                var=h3[j]
                h3[j]=h3[j-1]
                h3[j-1]=var

                var2=key3[j]
                key3[j]=key3[j-1]
                key3[j-1]=var2
            else:
                break
    for i in range(1,len(h4)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h4[j-1]<h4[j]:
                index=j
                var=h4[j]
                h4[j]=h4[j-1]
                h4[j-1]=var

                var2=key4[j]
                key4[j]=key4[j-1]
                key4[j-1]=var2
            else:
                break
    for i in range(1,len(h5)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h3[j-1]<h5[j]:
                index=j
                var=h5[j]
                h5[j]=h5[j-1]
                h5[j-1]=var

                var2=key5[j]
                key5[j]=key5[j-1]
                key5[j-1]=var2
            else:
                break
                
                
                
    for i in range(1,len(h6)):
        for j in range(i,0,-1):
            var=0
            var2=0
            if h6[j-1]<h6[j]:
                index=j
                var=h6[j]
                h6[j]=h6[j-1]
                h6[j-1]=var

                var2=key6[j]
                key6[j]=key6[j-1]
                key6[j-1]=var2
            else:
                break        
                
    '''       
    #basic1
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*alpha[1]
    for j in range(len(key3)):
        data2[2][key3[j]]=(j+1)*alpha[2]              
        
    for j in range(len(key4)):
        data2[3][key4[j]]=(j+1)*alpha[3]
        
                             
    for j in range(len(key5)):               
        data2[4][key5[j]]=(j+1)*alpha[4]
       
    for j in range(len(key6)):
        data2[5][key6[j]]=(j+1)*alpha[5]
    
    #basic2
            
    '''
    '''
    for j in range(len(key1)):    
        #data2[0][key1[j]]=((j+1)/((beta[0]*len(key1))*((beta[0]*len(key1))+1)/2)*alpha[0])
         
        data2[0][key1[j]]=(j+1)*alpha[0]
    for j in range(len(key2)):
        data2[1][key2[j]]=(j+1)*alpha[1]
    for j in range(len(key3)):
        if data1[2][key3[j]]==1 and data1[0][key3[j]]==1: 
            data2[2][key3[j]]=(j+1)*(len(key1)/len(key3))*alpha[2]
        else:
            data2[2][key3[j]]=(j+1)*(len(key2)/len(key3))*alpha[2]                  
        
    for j in range(len(key4)):
        if data1[3][key4[j]]==1 and data1[0][key4[j]]==1:                   
            data2[3][key4[j]]=(j+1)*(len(key1)/len(key4))*alpha[3]
        else :                     
            data2[3][key4[j]]=(j+1)*(len(key2)/len(key4))*alpha[3]
                             
    for j in range(len(key5)):
        if data1[4][key5[j]]==1 and data1[0][key5[j]]==1:                  
            data2[4][key5[j]]=(j+1)*(len(key1)/len(key5))*alpha[4]
        else:      
            data2[4][key5[j]]=(j+1)*(len(key2)/len(key5))*alpha[4]
    for j in range(len(key6)):
        if data1[5][key6[j]]==1 and data1[0][key6[j]]==1:                    
            data2[5][key6[j]]=(j+1)*(len(key1)/len(key6))*alpha[5]
        else:                    
             data2[5][key6[j]]=(j+1)*(len(key2)/len(key6))*alpha[5] 
          
    '''
    
    for j in range(len(key1)): 
        if y[key1[j]]==1:
            data2[0][key1[j]]=1
        else:
            data2[0][key1[j]]=2
    for j in range(len(key2)):
        if y[key2[j]]==1:
            data2[1][key2[j]]=1
        else:    
            data2[1][key2[j]]=2
    for j in range(len(key3)):
        if y[key3[j]]==1:
            data2[2][key3[j]]=1
        else:
            data2[2][key3[j]]=2
    for j in range(len(key4)):
        if y[key4[j]]==1:
            data2[3][key4[j]]=1
        else:
            data2[3][key4[j]]=2
    for j in range(len(key5)):
        if y[key5[j]]==1:
            data2[4][key5[j]]=1
        else:
            data2[4][key5[j]]=2
    for j in range(len(key6)):
        if y[key6[j]]==1:
            data2[5][key6[j]]=1 
        else:
            data2[5][key6[j]]=2
            
    for j in range(n):
        sum=0
        for i in range(m):
       
            sum=sum+data2[i][j] 
        cost[j]=sum
        
        
    ################
    Lp_prob = p.LpProblem('Problem', p.LpMinimize)  
   
    
#     X=np.zeros(n+1,dtype=p.LpVariable)
    X=np.zeros(n+m+1,dtype=p.LpVariable)
    sizes=np.zeros(m,dtype=int)
#     report_index(index,data1,e):  
    max_size=0
    for i in range(m):
        count=0
        for j in range(n):
            if data1[i][j]==1:
                count=count+1 
        if count>max_size:
            max_size=count
        sizes[i]=count
        
    #############################33
    
    
    
    
    ###############################
        
        
        
  
    select_sizes=np.zeros(m,dtype=int)
   
    size_final=np.zeros(m,dtype=int)

    
    for i in range(n):
        var1=str(i)       
        X[i]=p.LpVariable(var1,lowBound=0,upBound=1,cat='Integer')
   
    X[n]=p.LpVariable(str(n),lowBound=0,upBound=1,cat='Continuous')  

    #########objective function#####################
    
#     Lp_prob += 2*X[n+1]+10*X[n+2]+9*X[n+3]+3*X[n+4]
    Lp_prob+= p.lpSum([(X[j])*cost[j] for j in range(n)]) 
  
    

    ##############constraint#################
    for i in range(2*m):
        if i<m:

            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) >= math.floor(beta[i]*sizes[i])
            Lp_prob += p.lpSum([(X[j])*(data1[i][j]) for j in range(n)]) <= math.ceil((beta[i]+eps)*sizes[i])
           # Lp_prob += p.lpSum([(X[j])*(data1[i][j])*(sizes[i]-report_index(j,i,data1,e)+1) for j in range(n)]) <= X[n+i+1]

   
    #####################################
    status = Lp_prob.solve()   # Solver 
    print(p.LpStatus[status]) 
    print("objective is:")        
    print(p.value(Lp_prob.objective))
    print("discripency is:") 
    print(p.value(X[n]))
    x=np.zeros(n,dtype=float)

   # The solution status 
    Synth1={}
    Synth2={}
    # # Printing the final solution 
    for i in range(n):
        if(p.value(X[i])==1):
            Synth1[i]=1 
            Synth2[i]=-1
#             if(data1[2][i]==1):
#                 print("no")
        else:
            Synth1[i]=-1
            Synth2[i]=1
    Synthu1=Synth1  
    Synthu2=Synth2  
    
              
    return Synthu1,Synthu2   


In [21]:
# without accuracy
import time
# import pulp as p 
# from random import *
data= pd.read_csv('data/bank_train.csv',skipinitialspace=True)

print(data['marital'].value_counts())
#marital
#U=80, M=24928, S=11568, D=4612
# m_3, m_0, m_1, m_2
#age
#>60 and <25= a_1
#>=25and <=60 =a_2
# print(data.head())
# print(data.shape[0],data.shape[1])

#sensitive columns name 0='age',2='marital'

data_c = data.drop(columns=['age_group','y'])
# print(sens)
r=data[['y']]

X_test,Y_test_pred,Y_test,e = Bank_svm(data_c , r)

X_test.reset_index(drop=True, inplace=True)
# Y_test_pred.reset_index()
Y_test.reset_index(drop=True, inplace=True)
print(X_test)
print(Y_test_pred)
print(Y_test)
sens=X_test[['age','marital']]
print(sens)
p=sens.shape[0]

# for i in range(0,p):  
#     if r.loc[i,'y'] == 1 :
#                r.loc[i,"y"] = 1 
#     else: 
#                r.loc[i,"y"] = 0 
            
for i in range(0,p):
    if sens.loc[i,'age'] > 60 or sens.loc[i,'age'] < 25 :
               sens.loc[i,'age'] = 1 
    else :
               sens.loc[i,'age'] = 2  
            
sens1 = pd.get_dummies(sens, columns=['age','marital'], prefix =['a','m'])
print(sens1.head())
sensitive = sens1.T

print(sensitive)








0    24928
1    11568
2     4612
3       80
Name: marital, dtype: int64
There are 28831 samples in the training set and 12357 samples in the test set


/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The accuracy of the SVM classifier on training data is 0.92
The accuracy of the SVM classifier on test data is 0.91
####Train prediction Label###############################################
####Actual Train Label###############################################
[[0.93664901 0.06335099]
 [0.93204958 0.06795042]
 [0.9399619  0.0600381 ]
 ...
 [0.93542819 0.06457181]
 [0.93341507 0.06658493]
 [0.79605492 0.20394508]]
[0 0 0 ... 0 0 0]
####Change to colors###############################################
       age  job  marital  education  default  housing  loan  contact  month  \
0       39    3        0          3        0        1     0        1      2   
1       55    3        0          0        0        1     0        1      8   
2       39    3        0          3        1        0     0        0      1   
3       56    8        0          3        0        1     0        1      3   
4       49    3        0          3        0        1     0        1      5   
...    ...  ...      ...

/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:45: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/subham/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:43: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a

   a_1  a_2  m_0  m_1  m_2  m_3
0    0    1    1    0    0    0
1    0    1    1    0    0    0
2    0    1    1    0    0    0
3    0    1    1    0    0    0
4    0    1    1    0    0    0
     0      1      2      3      4      5      6      7      8      9      \
a_1      0      0      0      0      0      0      0      0      1      0   
a_2      1      1      1      1      1      1      1      1      0      1   
m_0      1      1      1      1      1      1      1      0      0      1   
m_1      0      0      0      0      0      0      0      1      1      0   
m_2      0      0      0      0      0      0      0      0      0      0   
m_3      0      0      0      0      0      0      0      0      0      0   

     ...  12347  12348  12349  12350  12351  12352  12353  12354  12355  12356  
a_1  ...      0      0      0      0      0      0      0      0      0      0  
a_2  ...      1      1      1      1      1      1      1      1      1      1  
m_0  ...      0      1   

In [24]:
accu_all,DP_all,acc_rate,alpha,prec,rec = main(sensitive, Y_test, Y_test_pred,e )


sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
579
213
0.36787564766839376
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
11778
1175
0.09976226863644082
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
7558
748
0.09896798094734056
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
3401
497
0.14613349014995589
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
1375
140
0.10181818181818182
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
23
3
0.13043478260869565
data acceptance rates
[0.36787564766839376, 0.09976226863644082, 0.09896798094734056, 0.14613349014995589, 0.10181818181818182, 0.13043478260869565]
data DP
0.2689076667210532
sensitive attribute  1
prec reca accuracy for each sens
0.7142857142857143 0.5633802816901409 0.7564766839378239
SVM----------total , accepted, aceeptance rate:
579
168
0.29015544041450775
sensitive attribute  2
pre

In [1]:
'''#check
print(acc_rate)
print(prec)
print(rec)
alpha=np.arange(0,1.2,.2)  
print(accu)
print(alpha)
'''

'\nprint(acc_rate)\nprint(prec)\nprint(rec)\nalpha=np.arange(0,1.2,.2)  \nprint(accu)\nprint(alpha)\n'

In [ ]:
weighted_precision=[]
weighted_recall=[]
p=[0,3]
r=[1,2,4]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
dp_list=[]
     
sizes=[579, 11778, 7558, 3401,1375]
for i in range(6):
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    acc_list=[]
    for j in range(5):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    wr=weight_rec/weight_r
    weighted_precision.append(wp)
    weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)  

In [20]:
#LP-5 without cv values

accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e )

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
579
213
0.36787564766839376
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
11778
1175
0.09976226863644082
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
7558
748
0.09896798094734056
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
3401
497
0.14613349014995589
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
1375
140
0.10181818181818182
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
23
3
0.13043478260869565
data acceptance rates
[0.36787564766839376, 0.09976226863644082, 0.09896798094734056, 0.14613349014995589, 0.10181818181818182, 0.13043478260869565]
data DP
0.2689076667210532
sensitive attribute  1
prec reca accuracy for each sens
0.7142857142857143 0.5633802816901409 0.7564766839378239
SVM----------total , accepted, aceeptance rate:
579
168
0.29015544041450775
sensitive attribute  2
pre

In [26]:
import numpy as np
acc_rate=[[0.2970639032815199, 0.06707420614705382, 0.07105054247155332, 0.10202881505439576, 0.056, 0.043478260869565216],
[0.25734024179620035, 0.06911190354898965, 0.0723736438211167, 0.09732431637753602, 0.06036363636363636, 0.08695652173913043],
[0.21243523316062177, 0.07123450500933945, 0.07369674517068008, 0.09232578653337253, 0.06472727272727273, 0.08695652173913043],
[0.16753022452504318, 0.07327220241127526, 0.07488753638528711, 0.08732725668920906, 0.06909090909090909, 0.08695652173913043],
[0.12435233160621761, 0.07539480387162506, 0.07621063773485048, 0.0826227580123493, 0.07345454545454545, 0.08695652173913043],
[0.08635578583765112, 0.07751740533197486, 0.07753373908441387, 0.07880035283740076, 0.07781818181818181, 0.08695652173913043]]

prec=[[0.7034883720930233, 0.6620253164556962, 0.6741154562383612, 0.6512968299711815, 0.7272727272727273, 0.0],
[0.7181208053691275, 0.6511056511056511, 0.6672760511882998, 0.6525679758308157, 0.6746987951807228, 0.0],
[0.7154471544715447, 0.6328963051251489, 0.6409335727109515, 0.6560509554140127, 0.6292134831460674, 0.0],
[0.6804123711340206, 0.6164542294322132, 0.6201413427561837, 0.6430976430976431, 0.5894736842105263, 0.0],
[0.6666666666666666, 0.5968468468468469, 0.5954861111111112, 0.6370106761565836, 0.5544554455445545, 0.0],
[0.7058823529411765, 0.5756578947368421, 0.5665529010238908, 0.6417910447761194, 0.5327102803738317, 0.0]]

rec=[[0.568075117370892, 0.4451063829787234, 0.4839572192513369, 0.45472837022132795, 0.4, 0.0],
[0.5023474178403756, 0.451063829787234, 0.4879679144385027, 0.4346076458752515, 0.4, 0.0],
[0.4131455399061033, 0.45191489361702125, 0.4772727272727273, 0.41448692152917505, 0.4, 0.0],
[0.30985915492957744, 0.45276595744680853, 0.4692513368983957, 0.3843058350100604, 0.4, 0.0],
[0.22535211267605634, 0.451063829787234, 0.4585561497326203, 0.36016096579476864, 0.4, 0.0],
[0.16901408450704225, 0.44680851063829785, 0.44385026737967914, 0.3460764587525151, 0.40714285714285714, 0.0]]

accu=[0.9140,0.9128,0.9100,0.9067, 0.9035, 0.9005]
weighted_precision=[]
weighted_recall=[]
p=[0,3]
r=[1,2,4]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
dp_list=[]
     
sizes=[579, 11778, 7558, 3401,1375]
for i in range(6):
    acc_list=[]
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    for j in range(5):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    wr=weight_rec/weight_r
    weighted_precision.append(wp)
    weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)   


[[0.2970639  0.25734024 0.21243523 0.16753022 0.12435233 0.08635579]
 [0.06707421 0.0691119  0.07123451 0.0732722  0.0753948  0.07751741]
 [0.07105054 0.07237364 0.07369675 0.07488754 0.07621064 0.07753374]
 [0.10202882 0.09732432 0.09232579 0.08732726 0.08262276 0.07880035]
 [0.056      0.06036364 0.06472727 0.06909091 0.07345455 0.07781818]
 [0.04347826 0.08695652 0.08695652 0.08695652 0.08695652 0.08695652]]
[0.658889519139158, 0.6621044301782234, 0.664691759246754, 0.6485260922265532, 0.6413249521629499, 0.6511148808131968] [0.456289490696973, 0.46114100162040683, 0.45772202644722854, 0.4552787915159377, 0.45040785895964397, 0.4430955718084552] [0.914, 0.9128, 0.91, 0.9067, 0.9035, 0.9005] [0.2410639032815199, 0.19697660543256398, 0.14770796043334905, 0.09843931543413409, 0.05089778615167216, 0.008838380505676258]


In [19]:
#without cv values--part 2

accu_all,DP_all,acceptance_rate,alpha_weight = main(sensitive, Y_test, Y_test_pred,e )

sensitive attribute  1
ACTUAL----------total ,accepted, aceeptance rate:
579
213
0.36787564766839376
sensitive attribute  2
ACTUAL----------total ,accepted, aceeptance rate:
11778
1175
0.09976226863644082
sensitive attribute  3
ACTUAL----------total ,accepted, aceeptance rate:
7558
748
0.09896798094734056
sensitive attribute  4
ACTUAL----------total ,accepted, aceeptance rate:
3401
497
0.14613349014995589
sensitive attribute  5
ACTUAL----------total ,accepted, aceeptance rate:
1375
140
0.10181818181818182
sensitive attribute  6
ACTUAL----------total ,accepted, aceeptance rate:
23
3
0.13043478260869565
data acceptance rates
[0.36787564766839376, 0.09976226863644082, 0.09896798094734056, 0.14613349014995589, 0.10181818181818182, 0.13043478260869565]
data DP
0.2689076667210532
sensitive attribute  1
prec reca accuracy for each sens
0.7142857142857143 0.5633802816901409 0.7564766839378239
SVM----------total , accepted, aceeptance rate:
579
168
0.29015544041450775
sensitive attribute  2
pre