In [7]:
#practice propub
import pandas as pd
df = pd.read_csv('propub.csv', header= None)
    
columns = ['0','1','2','3','4','5','6','7']


p=pd.read_csv('propub.csv', header=None, skiprows=1)

df11=p.iloc[0:3694,:]
df22=p.iloc[3694:5278,:]

#print(df1.shape[0],df2.shape[0])
p=int(64*(np.ceil(df1.shape[0]/64)-df1.shape[0]/64))
q=int(64*(np.ceil(df2.shape[0]/64)-df2.shape[0]/64))
#print(p,q)

df1=df11.append(df1.iloc[0:p,:])
df2=df22.append(df2.iloc[0:q,:])
#print(df11.shape[0],df22.shape[0])

df1.to_csv('propub_tr.csv',index=False,header=False)
df2.to_csv('propub_te.csv',index=False,header=False)


# f_in_tr = 'propub_tr.csv'
# f_in_te = 'propub_te.csv'

In [5]:
import numpy as np
print(df1.shape[0],df2.shape[0])
p=int(64*(np.ceil(df1.shape[0]/64)-df1.shape[0]/64))
q=int(64*(np.ceil(df2.shape[0]/64)-df2.shape[0]/64))
print(p,q)

df11=df1.append(df1.iloc[0:p,:])
df22=df2.append(df2.iloc[0:q,:])
#print(df11.shape[0],df22.shape[0])


3694 1584
18 16
3712 1600


In [4]:
k=df1.append(df2)
k.shape

(5278, 8)

In [45]:
k=2

p=np.ones(10)
t=p
n=p.shape[0]
print(n)
print(p)
p[n-k:n]=0

print(p.shape)
print(t)
np.sum(np.multiply(p,t))


10
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
[1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]


8.0

In [41]:
p=np.zeros((10,1),dtype=float)
print(p)
q=np.concatenate((p,[[1], [1], [1] ,[1]]))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [50]:
s=np.ones((14,1))
k=np.multiply(s,q)
print(q)
print(s)
print(k)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]]
