In [34]:
# adult
import numpy as np
acc_rate1=[[0.1227, 0.1336, 0.0663, 0.0260, 0.04, 0.1430, 0.0594],
[0.0911, 0.1113, 0.0524, 0.0260, 0.0266, 0.1061, 0.0463],
[0.0703, 0.0866, 0.0639, 0.0347, 0.0333, 0.0776, 0.0525],
[0.0753, 0.0940, 0.0827, 0.0782, 0.0933, 0.0772, 0.0757]]


recall1=[ [0.32484725050916496, 0.30952380952380953, 0.32098765432098764, 0.2, 0.2, 0.32260371959942774, 0.3247863247863248],
 [0.2701968771215207, 0.2777777777777778, 0.2962962962962963, 0.2, 0.13333333333333333, 0.26931330472103004, 0.2799145299145299],
[0.21181262729124237, 0.21428571428571427, 0.25308641975308643, 0.2, 0.13333333333333333, 0.2092274678111588, 0.23931623931623933],
[0.20196877121520707, 0.21428571428571427, 0.25925925925925924, 0.2, 0.13333333333333333, 0.2010014306151645, 0.22863247863247863]]

precision1= [[0.6678297278436846, 0.7222222222222222, 0.6419753086419753, 1.0, 0.5, 0.6843702579666161, 0.5868725868725869],
[0.7481203007518797, 0.7777777777777778, 0.75, 1.0, 0.5, 0.7699386503067485, 0.6485148514851485],
[0.7591240875912408, 0.7714285714285715, 0.5256410256410257, 0.75, 0.4, 0.8181818181818182, 0.4890829694323144],
[0.6761363636363636, 0.7105263157894737, 0.4158415841584158, 0.3333333333333333, 0.14285714285714285, 0.7893258426966292, 0.3242424242424242]]


accu=[0.7985,0.8027,0.7925,0.7812]
trend=[2,4,3,6,5,0,1]
acc_rate=np.zeros((4,7),dtype=float)
prec=np.zeros((4,7),dtype=float)
rec=np.zeros((4,7),dtype=float)

for j in range(7):
    for i in range(4):
        acc_rate[i,trend[j]]=acc_rate1[i][j]
        prec[i,trend[j]]=precision1[i][j]
        rec[i,trend[j]]=recall1[i][j]

print(acc_rate,prec,rec)    

import numpy as np

#P R P R P R R 
#0.7251,0.8101 0.5470,0.7329 0.6311,0.7389 0.5308,0.6172 0.6764,0.4776  0.4666,0.5333  0.2666,0.7333
#      
weighted_precision=[]
weighted_recall=[]
p=[0,1,2,3,4,5,6]
r=[]
print(np.transpose(acc_rate))

dp_list=[]
sizes=[9211, 4356, 11678,1220, 404, 150,115]
for i in range(4):
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    acc_list=[]
    for j in range(7):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    #wr=weight_rec/weight_r
    weighted_precision.append(wp)
    #weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)

[[0.143  0.0594 0.1227 0.0663 0.1336 0.04   0.026 ]
 [0.1061 0.0463 0.0911 0.0524 0.1113 0.0266 0.026 ]
 [0.0776 0.0525 0.0703 0.0639 0.0866 0.0333 0.0347]
 [0.0772 0.0757 0.0753 0.0827 0.094  0.0933 0.0782]] [[0.68437026 0.58687259 0.66782973 0.64197531 0.72222222 0.5
  1.        ]
 [0.76993865 0.64851485 0.7481203  0.75       0.77777778 0.5
  1.        ]
 [0.81818182 0.48908297 0.75912409 0.52564103 0.77142857 0.4
  0.75      ]
 [0.78932584 0.32424242 0.67613636 0.41584158 0.71052632 0.14285714
  0.33333333]] [[0.32260372 0.32478632 0.32484725 0.32098765 0.30952381 0.2
  0.2       ]
 [0.2693133  0.27991453 0.27019688 0.2962963  0.27777778 0.13333333
  0.2       ]
 [0.20922747 0.23931624 0.21181263 0.25308642 0.21428571 0.13333333
  0.2       ]
 [0.20100143 0.22863248 0.20196877 0.25925926 0.21428571 0.13333333
  0.2       ]]
[[0.143  0.1061 0.0776 0.0772]
 [0.0594 0.0463 0.0525 0.0757]
 [0.1227 0.0911 0.0703 0.0753]
 [0.0663 0.0524 0.0639 0.0827]
 [0.1336 0.1113 0.0866 0.094 ]
 [0.04

In [27]:
#bank
prec=[ [0.7889, 0.656, 0.6785, 0.6692307692307692, 0.6981132075471698, 0.0],
[0.7719298245614035, 0.6545454545454545, 0.6635514018691588, 0.6631578947368421, 0.7073170731707317, 0],
[0.775, 0.6416539050535988, 0.6533018867924528, 0.6367924528301887, 0.6666666666666666, 0],
[0.7333333333333333, 0.6422413793103449, 0.6597222222222222, 0.5974025974025974, 0.7307692307692307, 0]]

rec=[ [0.40375586854460094, 0.34893617021276596, 0.3810160427807487, 0.3501006036217304, 0.2642857142857143, 0.0],
[0.20657276995305165, 0.27574468085106385, 0.28475935828877, 0.2535211267605634, 0.20714285714285716, 0.0],
[0.14553990610328638, 0.3565957446808511, 0.37032085561497324, 0.2716297786720322, 0.2714285714285714, 0.0],
[0.051643192488262914, 0.12680851063829787, 0.1270053475935829, 0.0925553319919517, 0.1357142857142857, 0.0]]

acc_rate=[ [0.18825561312607944, 0.05306503650874512, 0.055570256681661816, 0.0764481034989709, 0.03854545454545454, 0.043478260869565216],
[0.09844559585492228, 0.04202750891492613, 0.04247155332098439, 0.055865921787709494, 0.029818181818181817, 0.0],
[0.0690846286701209, 0.0554423501443369, 0.05609949722148717, 0.06233460746839165, 0.04145454545454545, 0.0],
[0.025906735751295335, 0.019697741552046188, 0.01905265943371262, 0.022640399882387533, 0.01890909090909091, 0.0]]

accu=[ 0.9085,0.9025,0.9044,0.8935]

weighted_precision=[]
weighted_recall=[]
p=[0,1,2,3,4]
r=[]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
dp_list=[]
     
sizes=[579, 11778, 7558, 3401,1375]
for i in range(4):
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    acc_list=[]
    for j in range(5):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    #wr=weight_rec/weight_r
    weighted_precision.append(wp)
    weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list) 
weight_prec=weighted_precision
weight_rec=weighted_recall
accu==accu



[[0.18825561 0.0984456  0.06908463 0.02590674]
 [0.05306504 0.04202751 0.05544235 0.01969774]
 [0.05557026 0.04247155 0.0560995  0.01905266]
 [0.0764481  0.05586592 0.06233461 0.0226404 ]
 [0.03854545 0.02981818 0.04145455 0.01890909]
 [0.04347826 0.         0.         0.        ]]
[0.6701714635507352, 0.6641799118299896, 0.6490696266996389, 0.6484821776010175] [0.3025210084033613, 0.3025210084033613, 0.3025210084033613, 0.3025210084033613] [0.9085, 0.9025, 0.9044, 0.8935] [0.1497101585806249, 0.06862741403674047, 0.027630083215575446, 0.006997644842204425]


True

In [29]:
# propublica
acc_rate= [[0.25961538461538464, 0.51875, 0.430952380952381, 0.3611111111111111],
           [0.34615384615384615, 0.43125, 0.403968253968254, 0.3734567901234568],
           [0.27884615384615385, 0.20416666666666666, 0.23015873015873015, 0.24691358024691357],
           [0.2948717948717949, 0.2708333333333333, 0.2857142857142857, 0.25925925925925924]]


prec=[ [0.5925925925925926, 0.6546184738955824, 0.6611418047882136, 0.5384615384615384],
[0.41203703703703703, 0.6207729468599034, 0.5795677799607073, 0.4214876033057851],
[0.3735632183908046, 0.5357142857142857, 0.4827586206896552, 0.375],
[0.391304347826087, 0.6192307692307693, 0.5555555555555556, 0.39285714285714285]]


rec =[[0.40336134453781514, 0.6735537190082644, 0.5993322203672788, 0.5121951219512195],
[0.3739495798319328, 0.53099173553719, 0.49248747913188645, 0.4146341463414634],
[0.27310924369747897, 0.21694214876033058, 0.2337228714524207, 0.24390243902439024],
 [0.3025210084033613, 0.33264462809917356, 0.333889816360601, 0.2682926829268293]]

accu=[ 0.6603535353535354,  0.5833333333333334 ,0.5252525252525253, 0.5580808080808081]
weighted_precision=[]
weighted_recall=[]
p=[1,2]
r=[0,3]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
sizes=[624,960,1260,324]
dp_list=[]

for i in range(4):
    weight_prec=0
    weight_rec=0
    weight_p=0
    weight_r=0
    acc_list=[]
    for j in range(4):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    wr=weight_rec/weight_r
    weighted_precision.append(wp)
    weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)

[[0.25961538 0.34615385 0.27884615 0.29487179]
 [0.51875    0.43125    0.20416667 0.27083333]
 [0.43095238 0.40396825 0.23015873 0.28571429]
 [0.36111111 0.37345679 0.24691358 0.25925926]]
[0.6583209049427515, 0.597386230511711, 0.5056583677273332, 0.5830907830907831] [0.44055769884366225, 0.38785443167696226, 0.2631271712142714, 0.29082271994935666] [0.6603535353535354, 0.5833333333333334, 0.5252525252525253, 0.5580808080808081] [0.2591346153846154, 0.08509615384615388, 0.07467948717948719, 0.035612535612535634]


In [ ]:
adult
weighted prec
0.6605, 
0.7397,
0.7234,
0.6424,  
acc
0.7985, 
0.8027, 
0.7925, 
0.7812,

config 
0.1169 0.0853 0.0532 0.0186

bank

weighted prec
0.6701 0.6641 0.6490 0.6484 
acc
0.9085, 
 0.9025,
 0.9044,
 0.8935,
config
0.1497 0.0686 0.0276 0.0069


propub

prec
0.6583, 0.6640
0.5973, 0.6659
0.5056,0.7277
0.5830,0.6973
rec
0.4405, 0.4627
0.3878,0.5014
0.2631, 0.4071
0.2908,0.4487
acc
0.6603,0.6691
0.5833, 0.6489
0.5252,  0.6262
0.5580,0.6388
conf
0.2591 0.0850 0.0746 0.0356

In [36]:
# adult from LP5

prec=[[0.85041761579347, 0.7286821705426356, 0.8379888268156425, 0.65, 0.9259259259259259, 0.5, 1.0],
[0.8812691914022518, 0.7661691542288557, 0.8720602069614299, 0.6507936507936508, 0.9318181818181818, 0.6, 1.0],
[0.9131652661064426, 0.6929824561403509, 0.8963414634146342, 0.5194805194805194, 0.8529411764705882, 0.42857142857142855, 0.75],
[0.9127988748241913, 0.601823708206687, 0.8828213879408419, 0.39, 0.6, 0.23076923076923078, 0.625]]



rec=[[0.4005722460658083, 0.4017094017094017, 0.4073319755600815, 0.32098765432098764, 0.3968253968253968, 0.2, 0.2],
[0.30793991416309013, 0.32905982905982906, 0.31466395112016293, 0.25308641975308643, 0.3253968253968254, 0.2, 0.2],
[0.23319027181688126, 0.33760683760683763, 0.2494908350305499, 0.24691358024691357, 0.23015873015873015, 0.2, 0.2],
[0.2321173104434907, 0.4230769230769231, 0.263408010862186, 0.24074074074074073, 0.19047619047619047, 0.2, 0.3333333333333333]]

accu=[ 0.8361, 0.8222,0.8093,0.8076]
weighted_precision=[]
weighted_recall=[]
p=[0,1,2,3,4,5,6]
r=[]
print(np.transpose(acc_rate))

dp_list=[]
sizes=[9211, 4356, 11678,1220, 404, 150,115]
for i in range(4):
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    acc_list=[]
    for j in range(7):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    #wr=weight_rec/weight_r
    weighted_precision.append(wp)
    #weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)

[[0.143  0.1061 0.0776 0.0772]
 [0.0594 0.0463 0.0525 0.0757]
 [0.1227 0.0911 0.0703 0.0753]
 [0.0663 0.0524 0.0639 0.0827]
 [0.1336 0.1113 0.0866 0.094 ]
 [0.04   0.0266 0.0333 0.0933]
 [0.026  0.026  0.0347 0.0782]]
[0.8163353647668798, 0.8481663320610825, 0.8486092223098686, 0.8168207069338281] [] [0.8361, 0.8222, 0.8093, 0.8076] [0.11699999999999999, 0.0853, 0.05329999999999999, 0.018699999999999994]


In [30]:
#propub from LP5

prec=[[0.6172839506172839, 0.6606425702811245, 0.6666666666666666, 0.5726495726495726],
[0.5416666666666666, 0.678743961352657, 0.656188605108055, 0.5289256198347108],
[0.5862068965517241, 0.7551020408163265, 0.7068965517241379, 0.5625],
[0.592391304347826, 0.7230769230769231, 0.6777777777777778, 0.6309523809523809]]

rec=[[0.42016806722689076, 0.6797520661157025, 0.6043405676126878, 0.5447154471544715],
[0.49159663865546216, 0.5805785123966942, 0.5575959933222037, 0.5203252032520326],
[0.42857142857142855, 0.30578512396694213, 0.34223706176961605, 0.36585365853658536],
[0.4579831932773109, 0.3884297520661157, 0.4073455759599332, 0.43089430894308944]]

accu=[0.6691,0.6489,0.6262,0.6388]
weighted_precision=[]
weighted_recall=[]
p=[1,2]
r=[0,3]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
sizes=[624,960,1260,324]
dp_list=[]

for i in range(4):
    weight_prec=0
    weight_rec=0
    weight_p=0
    weight_r=0
    acc_list=[]
    for j in range(4):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    wr=weight_rec/weight_r
    weighted_precision.append(wp)
    weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list)

[[0.25961538 0.34615385 0.27884615 0.29487179]
 [0.51875    0.43125    0.20416667 0.27083333]
 [0.43095238 0.40396825 0.23015873 0.28571429]
 [0.36111111 0.37345679 0.24691358 0.25925926]]
[0.6640616520134592, 0.6659422726732883, 0.7277421686288681, 0.6973665973665973] [0.46273489327808925, 0.5014152619985938, 0.40713624134433024, 0.4487249669858681] [0.6691, 0.6489, 0.6262, 0.6388] [0.2591346153846154, 0.08509615384615388, 0.07467948717948719, 0.035612535612535634]


In [39]:
#bank LP-5 

prec=[[0.7798165137614679, 0.656, 0.6864608076009501, 0.6884615384615385, 0.5192307692307693, 0.0],
[0.7368421052631579, 0.6747474747474748, 0.6915887850467289, 0.7052631578947368, 0.4878048780487805, 0],
[0.75, 0.6722817764165391, 0.6863207547169812, 0.6933962264150944, 0.543859649122807, 0],
[0.6666666666666666, 0.7370689655172413, 0.7291666666666666, 0.7662337662337663, 0.6538461538461539, 0]]


rec=[[0.39906103286384975, 0.34893617021276596, 0.38636363636363635, 0.36016096579476864, 0.19285714285714287, 0.0],
[0.19718309859154928, 0.28425531914893615, 0.2967914438502674, 0.26961770623742454, 0.14285714285714285, 0.0],
[0.14084507042253522, 0.37361702127659574, 0.3890374331550802, 0.29577464788732394, 0.22142857142857142, 0.0],
[0.046948356807511735, 0.14553191489361703, 0.14037433155080214, 0.11871227364185111, 0.12142857142857143, 0.0]]
 
    
accu=[0.9083,0.9038,0.9075,0.8969]

weighted_precision=[]
weighted_recall=[]
p=[0,1,2,3,4]
r=[]
print(np.transpose(acc_rate))
weight_prec=0
weight_p=0
weight_rec=0
weight_r=0
dp_list=[]
     
sizes=[579, 11778, 7558, 3401,1375]
for i in range(4):
    weight_prec=0
    weight_p=0
    weight_rec=0
    weight_r=0
    acc_list=[]
    for j in range(5):
        #print(j)
        if j in p:
            weight_prec=weight_prec+sizes[j]*prec[i][j]
            weight_p=weight_p+sizes[j]
            #print(j)
        if j in r:    
            weight_rec=weight_rec+sizes[j]*rec[i][j]
            weight_r=weight_r+sizes[j]
        #print(acc_rate[i][j])    
        acc_list.append(acc_rate[i][j])
    #print(acc_list)
    dp=max(acc_list)-min(acc_list)   
    dp_list.append(dp)     
    wp=weight_prec/weight_p
    #wr=weight_rec/weight_r
    weighted_precision.append(wp)
    #weighted_recall.append(wr)
print(weighted_precision, weighted_recall,accu,dp_list) 
weight_prec=weighted_precision
weight_rec=weighted_recall
accu==accu



[[0.143  0.1061 0.0776 0.0772]
 [0.0594 0.0463 0.0525 0.0757]
 [0.1227 0.0911 0.0703 0.0753]
 [0.0663 0.0524 0.0639 0.0827]
 [0.1336 0.1113 0.0866 0.094 ]
 [0.04   0.0266 0.0333 0.0933]
 [0.026  0.026  0.0347 0.0782]]
[0.6650825217818587, 0.6751515564871159, 0.674158382016384, 0.7323818169789897] [] [0.9083, 0.9038, 0.9075, 0.8969] [0.08359999999999998, 0.065, 0.0341, 0.018699999999999994]


True

In [ ]:

\begin{table*}
\begin{tabular}{|p{2cm}|p{2cm}|p{2cm}|p{2cm}|p{2cm}|}
\hline
\multirow{4}{*}{Adult Dataset} & 
  \Longstack{Config-1 \\ $DP_1 = 0.1698$}  & \Longstack{Config-2 \\ $DP_1 = 0.1618$} & \Longstack{Config-3 \\ $DP_1 = 0.157$} & \Longstack{Config-4 \\ $DP_1 = 0.1074$} \\
\cline{2-5}
&\multirow{3}{*}{\parbox{3cm}{ 
0.7643, 0.7531 \\  0.6286, 0.6136 \\ 0.8519, 0.8511}}&
	\multirow{3}{*}{\parbox{3cm}{0.7623, {\bf 0.7702} \\	0.6410, {\bf 0.6424} \\ 0.8511, 0.8502}}
	&\multirow{3}{*}{\parbox{3cm}{0.7681, {\bf 0.7814} \\	0.5902,	{\bf 0.6387} \\ 0.8418,  0.8404}}
	&\multirow{3}{*}{\parbox{3cm}{0.7524, {\bf 0.8089} \\	0.6021, {\bf 0.6585} \\0.8357, {\bf 0.8519}}} \\
	&&&&\\
	&&&&\\

\hline 
\multirow{3}{*}{Bank Dataset} 	& 
   \Longstack{$DP_1 = 0.1715$}  &  \Longstack{$DP_1 = 0.0849$} & \Longstack{$DP_1 = 0.0495$} & \Longstack{$DP_1 = 0.0656$} \\
\cline{2-5}
&\multirow{2}{*}{\parbox{3cm}{0.6302, {\bf 0.6924}	\\ NA \\0.9065, {\bf 0.9083}}}
 &\multirow{2}{*}{\parbox{3cm}{0.6433, {\bf 0.6948} \\ NA \\ 0.9064, {\bf 0.9080}}}
& \multirow{2}{*}{\parbox{3cm}{0.6653, {\bf 0.6915} \\ NA \\ 0.9036, {\bf 0.9073}}}
& \multirow{2}{*}{\parbox{3cm}{0.6370, {\bf 0.6893} \\ NA \\ 0.9027, {\bf 0.9079}}}\\
&&&&\\
&&&&\\

\hline
\multirow{3}{*}{\parbox{2cm}{COMPAS Dataset}}
& 
   \Longstack{$DP_1 = 0.1482$}  &  \Longstack{$DP_1 = 0.0092$} & \Longstack{$DP_1 = 0.07$} & \Longstack{$DP_1 = 0.0668$} \\
\cline{2-5}
&\multirow{2}{*}{\parbox{3cm}{0.6021, {\bf 0.6348}\\	0.6288, 0.6260  \\ 0.6654, {\bf 0.6831}
}}&\multirow{2}{*}{\parbox{3cm}{ 0.6181, {\bf 0.6250} \\0.6412, 0.6100 \\ 0.6622, {\bf 0.6752}
}}&
\multirow{2}{*}{\parbox{3cm}{ 0.6028, {\bf 0.6237} \\0.6537, 0.6177 \\ 0.6554, {\bf 0.6600}}
}&
\multirow{2}{*}{\parbox{3cm}{ 0.5881, {\bf 0.6250} \\0.6606, 0.6190 \\ 0.6559, {\bf 0.6601} }}\\
&&&&\\
&&&&\\

\hline
\end{tabular}
\caption{Comparison of performance of {\bf LP-3} (multi-attribute case) with different configurations of Zafar et al. \cite{zafar2019fairness} w.r.t. weighted precision, weighted recall and overall accuracy which correspond to first, second and third rows respectively of each cell. The second value in every pair of values represent results of {\bf LP-3}, bold values represent improvement and NA represents that for a particular configuration that metric is not to be compared.}
\label{table:agarwal_comparison}
\end{table*}